#pragma once

// PTX for pybind/src/cuda/nv12_to_rgb.cl, JIT-compiled by the CUDA driver (see
// CudaDriver::nv12_to_rgb). Generated - regenerate it from the .cl file, as
// described there, rather than editing it by hand.
static const char kNv12ToRgbPtx[] = R"PTX(
//
// Generated by LLVM NVPTX Back-End
//

.version 4.2
.target sm_50
.address_size 64

	// .globl	nv12_to_rgb             // -- Begin function nv12_to_rgb
                                        // @nv12_to_rgb
.visible .entry nv12_to_rgb(
	.param .u64 .ptr .global .align 1 nv12_to_rgb_param_0,
	.param .u64 .ptr .global .align 1 nv12_to_rgb_param_1,
	.param .u64 .ptr .global .align 1 nv12_to_rgb_param_2,
	.param .u32 nv12_to_rgb_param_3,
	.param .u32 nv12_to_rgb_param_4,
	.param .u32 nv12_to_rgb_param_5,
	.param .u32 nv12_to_rgb_param_6,
	.param .u32 nv12_to_rgb_param_7,
	.param .f32 nv12_to_rgb_param_8,
	.param .f32 nv12_to_rgb_param_9,
	.param .f32 nv12_to_rgb_param_10,
	.param .f32 nv12_to_rgb_param_11,
	.param .f32 nv12_to_rgb_param_12,
	.param .f32 nv12_to_rgb_param_13,
	.param .f32 nv12_to_rgb_param_14,
	.param .f32 nv12_to_rgb_param_15
)
{
	.reg .pred 	%p<11>;
	.reg .b16 	%rs<10>;
	.reg .b32 	%r<18>;
	.reg .f32 	%f<48>;
	.reg .b64 	%rd<17>;

// %bb.0:
	ld.param.u32 	%r5, [nv12_to_rgb_param_5];
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %tid.x;
	mad.lo.s32 	%r1, %r7, %r8, %r9;
	ld.param.u32 	%r10, [nv12_to_rgb_param_6];
	mov.u32 	%r12, %ctaid.y;
	mov.u32 	%r13, %ntid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r15, %r12, %r13, %r14;
	setp.ge.u32 	%p1, %r1, %r5;
	setp.ge.u32 	%p2, %r15, %r10;
	or.pred  	%p3, %p1, %p2;
	@%p3 bra 	$L__BB0_14;
// %bb.1:
	ld.param.f32 	%f22, [nv12_to_rgb_param_14];
	ld.param.f32 	%f21, [nv12_to_rgb_param_13];
	ld.param.f32 	%f20, [nv12_to_rgb_param_12];
	ld.param.f32 	%f19, [nv12_to_rgb_param_11];
	ld.param.f32 	%f18, [nv12_to_rgb_param_10];
	ld.param.f32 	%f17, [nv12_to_rgb_param_9];
	ld.param.f32 	%f16, [nv12_to_rgb_param_8];
	ld.param.u32 	%r6, [nv12_to_rgb_param_7];
	ld.param.u32 	%r4, [nv12_to_rgb_param_4];
	ld.param.u32 	%r3, [nv12_to_rgb_param_3];
	ld.param.u64 	%rd8, [nv12_to_rgb_param_2];
	ld.param.u64 	%rd7, [nv12_to_rgb_param_1];
	ld.param.u64 	%rd6, [nv12_to_rgb_param_0];
	cvt.u64.u32 	%rd1, %r15;
	mul.wide.u32 	%rd9, %r3, %r15;
	add.s64 	%rd10, %rd6, %rd9;
	cvt.u64.u32 	%rd2, %r1;
	mul.wide.u32 	%rd11, %r6, %r1;
	add.s64 	%rd3, %rd10, %rd11;
	shr.u32 	%r16, %r15, 1;
	mul.wide.u32 	%rd12, %r4, %r16;
	add.s64 	%rd13, %rd7, %rd12;
	and.b32  	%r17, %r1, 2147483646;
	mul.wide.u32 	%rd14, %r6, %r17;
	add.s64 	%rd4, %rd13, %rd14;
	setp.ne.s32 	%p4, %r6, 1;
	@%p4 bra 	$L__BB0_3;
// %bb.2:
	ld.global.u8 	%rs4, [%rd3];
	cvt.rn.f32.u16 	%f44, %rs4;
	ld.global.u8 	%rs5, [%rd4];
	cvt.rn.f32.u16 	%f43, %rs5;
	ld.global.u8 	%rs6, [%rd4+1];
	cvt.rn.f32.u16 	%f42, %rs6;
	bra.uni 	$L__BB0_4;
$L__BB0_3:
	ld.global.u16 	%rs1, [%rd3];
	cvt.rn.f32.u16 	%f44, %rs1;
	ld.global.u16 	%rs2, [%rd4];
	cvt.rn.f32.u16 	%f43, %rs2;
	ld.global.u16 	%rs3, [%rd4+2];
	cvt.rn.f32.u16 	%f42, %rs3;
$L__BB0_4:
	ld.param.f32 	%f23, [nv12_to_rgb_param_15];
	sub.rn.f32 	%f25, %f44, %f16;
	mul.rn.f32 	%f26, %f17, %f25;
	sub.rn.f32 	%f27, %f43, %f18;
	mul.rn.f32 	%f28, %f19, %f27;
	sub.rn.f32 	%f29, %f42, %f18;
	mul.rn.f32 	%f30, %f19, %f29;
	fma.rn.f32 	%f10, %f20, %f30, %f26;
	neg.f32 	%f31, %f21;
	fma.rn.f32 	%f32, %f31, %f28, %f26;
	neg.f32 	%f33, %f22;
	fma.rn.f32 	%f11, %f33, %f30, %f32;
	cvt.u64.u32 	%rd15, %r5;
	mad.lo.s64 	%rd16, %rd15, %rd1, %rd2;
	mad.lo.s64 	%rd5, %rd16, 3, %rd8;
	setp.lt.f32 	%p5, %f10, 0f00000000;
	mov.f32 	%f46, 0f00000000;
	mov.f32 	%f45, %f46;
	@%p5 bra 	$L__BB0_7;
// %bb.5:
	setp.gt.f32 	%p6, %f10, 0f3F800000;
	mov.f32 	%f45, 0f3F800000;
	@%p6 bra 	$L__BB0_7;
// %bb.6:
	mov.f32 	%f45, %f10;
$L__BB0_7:
	fma.rn.f32 	%f12, %f23, %f28, %f26;
	fma.rn.f32 	%f36, %f45, 0f437F0000, 0f3F000000;
	cvt.rzi.s16.f32 	%rs7, %f36;
	st.global.u8 	[%rd5], %rs7;
	setp.lt.f32 	%p7, %f11, 0f00000000;
	@%p7 bra 	$L__BB0_10;
// %bb.8:
	setp.gt.f32 	%p8, %f11, 0f3F800000;
	mov.f32 	%f46, 0f3F800000;
	@%p8 bra 	$L__BB0_10;
// %bb.9:
	mov.f32 	%f46, %f11;
$L__BB0_10:
	fma.rn.f32 	%f39, %f46, 0f437F0000, 0f3F000000;
	cvt.rzi.s16.f32 	%rs8, %f39;
	st.global.u8 	[%rd5+1], %rs8;
	setp.lt.f32 	%p9, %f12, 0f00000000;
	mov.f32 	%f47, 0f00000000;
	@%p9 bra 	$L__BB0_13;
// %bb.11:
	setp.gt.f32 	%p10, %f12, 0f3F800000;
	mov.f32 	%f47, 0f3F800000;
	@%p10 bra 	$L__BB0_13;
// %bb.12:
	mov.f32 	%f47, %f12;
$L__BB0_13:
	fma.rn.f32 	%f41, %f47, 0f437F0000, 0f3F000000;
	cvt.rzi.s16.f32 	%rs9, %f41;
	st.global.u8 	[%rd5+2], %rs9;
$L__BB0_14:
	ret;
                                        // -- End function
}
)PTX";
