"""Low-level pybind11 bindings around Chiaki, the PS4/PS5 Remote Play client library: discover consoles
(DiscoveryManager), register with one (Backend), connect and stream one (ChiakiPySession) and pull its
decoded frames (FrameHandler and subclasses). Most users want the pythonic wrapper in the `chiaki_py`
package instead of this module directly.

The sections between the <litgen_stub_*> markers are generated by pybind/bindings/generate_bindings.py
from the C++ headers; the rest is written by hand, like the bindings it describes
(pybind/bindings/pydef_chiaki.cpp and pydef_event_source.cpp).
"""

# ruff: noqa: E501
from __future__ import annotations

import enum
from typing import Any, Callable, Dict, List, Optional, overload

import numpy as np

from . import core as core
from .core.common import Codec, Target
from .core.log import LogLevel

####################    chiaki's C types (pydef_chiaki.cpp)    ####################

class DisableAudioVideo(enum.IntEnum):
    """Which of the audio/video streams to skip receiving, as returned by Settings.get_audio_video_disabled()."""

    None_ = 0
    Audio = 1
    Video = 2
    AudioVideo = 3

class VideoResolutionPreset(enum.IntEnum):
    """The resolution presets Settings' get/set_resolution_local_ps4/ps5 and .../remote_ps4/ps5
    methods store; the actual pixel dimensions negotiated end up in ChiakiPySession.get_video_profile()."""

    Resolution360p = 1
    Resolution540p = 2
    Resolution720p = 3
    Resolution1080p = 4

class VideoFPSPreset(enum.IntEnum):
    """The frame rate presets Settings' get/set_fpslocal/remote_ps4/ps5 methods store."""

    FPS30 = 30
    FPS60 = 60

class QuitReason(enum.IntEnum):
    """Why a ChiakiPySession ended, as passed to ChiakiPySession.on_session_quit() subscribers.
    See quit_reason_is_error() and quit_reason_string()."""

    None_ = 0
    Stopped = 1
    SessionRequestUnknown = 2
    SessionRequestConnectionRefused = 3
    SessionRequestRpInUse = 4
    SessionRequestRpCrash = 5
    SessionRequestRpVersionMismatch = 6
    CtrlUnknown = 7
    CtrlConnectFailed = 8
    CtrlConnectionRefused = 9
    StreamConnectionUnknown = 10
    StreamConnectionRemoteDisconnected = 11
    StreamConnectionRemoteShutdown = 12
    PsnRegistFailed = 13

def quit_reason_is_error(reason: QuitReason) -> bool:
    """True if `reason` means the session failed, False for a normal stop or console shutdown."""

def quit_reason_string(reason: QuitReason) -> str:
    """A human-readable description of `reason`."""

class FfmpegDecoder:
    """An opaque handle to a ChiakiPySession's FFmpeg decoder, as returned by
    ChiakiPySession.get_ffmpeg_decoder(). Not usable from Python beyond passing it back around;
    ChiakiPySession.has_hardware_decoder() and .hardware_decoder_type() are how to inspect it."""

class ChiakiConnectVideoProfile:
    """The stream's video settings, as returned by ChiakiPySession.get_video_profile(): the requested
    ones until the console answers, then the negotiated ones."""

    width: int
    height: int
    max_fps: int
    bitrate: int
    codec: Codec

class DiscoveryHostState(enum.IntEnum):
    """A discovered console's power state (DiscoveryHost.state): Ready to stream, Standby (needs a
    wakeup packet first, see DiscoveryManager.send_wakeup()), or Unknown before a reply is parsed."""

    Unknown = 0
    Ready = 1
    Standby = 2

class RegisteredHost:
    """The result of a successful registration, as delivered through RegistEvent.registered_host by
    Backend.register_host_async(). Backend.register_host() (the blocking variant) returns the
    equivalent information as a RegistResult instead."""

    @property
    def target(self) -> Target: ...
    @property
    def ap_ssid(self) -> str: ...
    @property
    def ap_bssid(self) -> str: ...
    @property
    def ap_key(self) -> str: ...
    @property
    def ap_name(self) -> str: ...
    @property
    def server_mac(self) -> List[int]: ...
    @property
    def server_nickname(self) -> str: ...
    @property
    def rp_regist_key(self) -> str: ...
    @property
    def rp_key_type(self) -> int: ...
    @property
    def rp_key(self) -> List[int]: ...
    @property
    def console_pin(self) -> int: ...

class RegistEventType(enum.IntEnum):
    """How a Backend.register_host_async() attempt ended: FINISHED_SUCCESS (registered_host is set),
    FINISHED_FAILED (wrong PIN, console unreachable, ...) or FINISHED_CANCELED."""

    FINISHED_CANCELED = 0
    FINISHED_FAILED = 1
    FINISHED_SUCCESS = 2

class RegistEvent:
    """Delivered to Backend.register_host_async()'s `on_next` callback once registration finishes;
    `type` says how (see RegistEventType), and `registered_host` carries the result if it succeeded."""

    @property
    def type(self) -> RegistEventType: ...
    @property
    def registered_host(self) -> RegisteredHost: ...

####################    Event sources (pydef_event_source.cpp)    ####################

OnNext = Callable[[Any], None]
OnError = Callable[[int, str], None]
OnCompleted = Callable[[], None]

class Subscription:
    def unsubscribe(self) -> None: ...

class EventSource:
    def subscribe(self, on_next: OnNext, on_error: Optional[OnError] = None, on_completed: Optional[OnCompleted] = None) -> Subscription: ...

class ChiakiQuitReasonEventSourceSubscription:
    def unsubscribe(self) -> None: ...

class ChiakiQuitReasonEventSource:
    def subscribe(self, on_next: OnNext, on_error: Optional[OnError] = None, on_completed: Optional[OnCompleted] = None) -> ChiakiQuitReasonEventSourceSubscription: ...

class BoolEventSourceSubscription:
    def unsubscribe(self) -> None: ...

class BoolEventSource:
    def subscribe(self, on_next: OnNext, on_error: Optional[OnError] = None, on_completed: Optional[OnCompleted] = None) -> BoolEventSourceSubscription: ...

class DoubleEventSourceSubscription:
    def unsubscribe(self) -> None: ...

class DoubleEventSource:
    def subscribe(self, on_next: OnNext, on_error: Optional[OnError] = None, on_completed: Optional[OnCompleted] = None) -> DoubleEventSourceSubscription: ...

class StringEventSourceSubscription:
    def unsubscribe(self) -> None: ...

class StringEventSource:
    def subscribe(self, on_next: OnNext, on_error: Optional[OnError] = None, on_completed: Optional[OnCompleted] = None) -> StringEventSourceSubscription: ...

class RegisteredHostEventSourceSubscription:
    def unsubscribe(self) -> None: ...

class RegisteredHostEventSource:
    def subscribe(self, on_next: OnNext, on_error: Optional[OnError] = None, on_completed: Optional[OnCompleted] = None) -> RegisteredHostEventSourceSubscription: ...

class RegistEventSourceSubscription:
    """Returned by RegistEventSource.subscribe(); call unsubscribe() to stop receiving callbacks."""

    def unsubscribe(self) -> None: ...

class RegistEventSource:
    """What Backend.register_host_async() returns: a one-shot stream of registration progress that
    calls `on_next` with the final RegistEvent once registration succeeds, `on_error` if it fails,
    and `on_completed` in either case."""

    def subscribe(self, on_next: OnNext, on_error: Optional[OnError] = None, on_completed: Optional[OnCompleted] = None) -> RegistEventSourceSubscription:
        """Register callbacks for this registration attempt and return a subscription that can be
        unsubscribe()'d. Registration only actually starts once the first subscriber attaches."""

# <litgen_stub_settings> // Autogenerated code below! Do not edit!
####################    <generated_from:settings.h>    ####################
# SPDX-License-Identifier: LicenseRef-AGPL-3.0-only-OpenSSL

# #ifndef CHIAKI_PY_SETTINGS_H
#




class RumbleHapticsIntensity(enum.IntEnum):
    """ How strongly the controller rumbles for haptic feedback, from Settings.get/set_rumble_haptics_intensity()."""
    Off = enum.auto()        # (= 0)
    VeryWeak = enum.auto()   # (= 1)
    Weak = enum.auto()       # (= 2)
    Normal = enum.auto()     # (= 3)
    Strong = enum.auto()     # (= 4)
    VeryStrong = enum.auto() # (= 5)

class Decoder(enum.IntEnum):
    """ The decoder implementation stored by Settings.get/set_decoder(). Only Ffmpeg is implemented and
     it is always used, whatever is set; Pi (chiaki-ng's Raspberry Pi decoder) is accepted but ignored.
    """
    Ffmpeg = enum.auto() # (= 0)
    Pi = enum.auto()     # (= 1)


class Settings:
    """ In-memory connection/decoding/UI settings, passed to ChiakiPySessionConnectInfo.
     A fresh instance starts at chiaki-ng's defaults; nothing is persisted. Most get_/set_ pairs
     are self-explanatory config knobs; set_log_level()/set_log_verbose() are the ones most callers
     need to touch directly (chiaki_py.Session sets the hardware decoder from its frame_handler_cls).
    """
    def __init__(self) -> None:
        pass

    def get_audio_video_disabled(self) -> DisableAudioVideo:
        pass

    def get_log_verbose(self) -> bool:
        pass
    def set_log_verbose(self, log_verbose: bool) -> None:
        pass

    def get_log_level(self) -> LogLevel:
        """ The least severe log level that is still logged; the levels are single bits ordered
         ERROR < WARNING < INFO < VERBOSE < DEBUG.
        """
        pass

    def set_log_level(self, log_level: LogLevel) -> None:
        """ Set the least severe log level that is still logged, e.g. LogLevel.DEBUG to see
         everything. Defaults to LogLevel.WARNING (LogLevel.DEBUG in a debug build of the module).
         VERBOSE is additionally controlled by set_log_verbose.
        """
        pass

    def get_log_level_mask(self) -> int:
        pass

    def get_rumble_haptics_intensity(self) -> RumbleHapticsIntensity:
        pass
    def set_rumble_haptics_intensity(
        self,
        rumble_haptics_intensity: RumbleHapticsIntensity
        ) -> None:
        pass

    def get_buttons_by_position(self) -> bool:
        pass
    def set_buttons_by_position(self, buttons_by_position: bool) -> None:
        pass

    def get_start_mic_unmuted(self) -> bool:
        pass
    def set_start_mic_unmuted(self, start_mic_unmuted: bool) -> None:
        pass

    def get_haptic_override(self) -> float:
        pass
    def set_haptic_override(self, haptic_override: float) -> None:
        pass

    def get_resolution_local_ps4(self) -> VideoResolutionPreset:
        pass
    def get_resolution_remote_ps4(self) -> VideoResolutionPreset:
        pass
    def get_resolution_local_ps5(self) -> VideoResolutionPreset:
        pass
    def get_resolution_remote_ps5(self) -> VideoResolutionPreset:
        pass
    def set_resolution_local_ps4(
        self,
        resolution_local_ps4: VideoResolutionPreset
        ) -> None:
        pass
    def set_resolution_remote_ps4(
        self,
        resolution_remote_ps4: VideoResolutionPreset
        ) -> None:
        pass
    def set_resolution_local_ps5(
        self,
        resolution_local_ps5: VideoResolutionPreset
        ) -> None:
        pass
    def set_resolution_remote_ps5(
        self,
        resolution_remote_ps5: VideoResolutionPreset
        ) -> None:
        pass

    def get_fpslocal_ps4(self) -> VideoFPSPreset:
        pass
    def get_fpsremote_ps4(self) -> VideoFPSPreset:
        pass
    def get_fpslocal_ps5(self) -> VideoFPSPreset:
        pass
    def get_fpsremote_ps5(self) -> VideoFPSPreset:
        pass
    def set_fpslocal_ps4(self, fps_local_ps4: VideoFPSPreset) -> None:
        pass
    def set_fpsremote_ps4(self, fps_remote_ps4: VideoFPSPreset) -> None:
        pass
    def set_fpslocal_ps5(self, fps_local_ps5: VideoFPSPreset) -> None:
        pass
    def set_fpsremote_ps5(self, fps_remote_ps5: VideoFPSPreset) -> None:
        pass

    def get_bitrate_local_ps4(self) -> int:
        pass
    def get_bitrate_remote_ps4(self) -> int:
        pass
    def get_bitrate_local_ps5(self) -> int:
        pass
    def get_bitrate_remote_ps5(self) -> int:
        pass
    def set_bitrate_local_ps4(self, bitrate_local_ps4: int) -> None:
        pass
    def set_bitrate_remote_ps4(self, bitrate_remote_ps4: int) -> None:
        pass
    def set_bitrate_local_ps5(self, bitrate_local_ps5: int) -> None:
        pass
    def set_bitrate_remote_ps5(self, bitrate_remote_ps5: int) -> None:
        pass

    def get_codec_ps4(self) -> Codec:
        pass
    def get_codec_local_ps5(self) -> Codec:
        pass
    def get_codec_remote_ps5(self) -> Codec:
        pass
    def set_codec_ps4(self, codec_ps4: Codec) -> None:
        pass
    def set_codec_local_ps5(self, codec_local_ps5: Codec) -> None:
        pass
    def set_codec_remote_ps5(self, codec_remote_ps5: Codec) -> None:
        pass

    def get_display_target_contrast(self) -> int:
        pass
    def set_display_target_contrast(self, display_target_contrast: int) -> None:
        pass

    def get_display_target_peak(self) -> int:
        pass
    def set_display_target_peak(self, display_target_peak: int) -> None:
        pass

    def get_display_target_trc(self) -> int:
        pass
    def set_display_target_trc(self, display_target_trc: int) -> None:
        pass

    def get_display_target_prim(self) -> int:
        pass
    def set_display_target_prim(self, display_target_prim: int) -> None:
        pass

    def get_decoder(self) -> Decoder:
        pass

    def set_decoder(self, decoder: Decoder) -> None:
        """ Currently ignored, see Decoder."""
        pass

    def get_hardware_decoder(self) -> str:
        pass
    def set_hardware_decoder(self, hardware_decoder: str) -> None:
        pass

    def get_packet_loss_max(self) -> float:
        pass
    def set_packet_loss_max(self, packet_loss_max: float) -> None:
        pass

    def get_audio_volume(self) -> int:
        pass

    def set_audio_volume(self, audio_volume: int) -> None:
        """ Stored only: playback does not apply it yet."""
        pass

    def get_audio_buffer_size_default(self) -> int:
        pass

    def get_audio_buffer_size_raw(self) -> int:
        """ The audio buffer size as set, 0 if set to "automatic"."""
        pass

    def get_audio_buffer_size(self) -> int:
        """ The audio buffer size to use: the default one if get_audio_buffer_size_raw() is 0."""
        pass

    def set_audio_buffer_size(self, audio_buffer_size: int) -> None:
        pass

    def get_audio_out_device(self) -> str:
        pass

    def set_audio_out_device(self, audio_out_device: str) -> None:
        """ Stored only: pass the device to chiaki_py.AudioSink or AudioOutput.open() instead."""
        pass

    def get_audio_in_device(self) -> str:
        pass

    def set_audio_in_device(self, audio_in_device: str) -> None:
        """ Stored only: there is no microphone input yet."""
        pass

    def get_psn_auth_token(self) -> str:
        pass
    def set_psn_auth_token(self, psn_auth_token: str) -> None:
        pass

    def get_dpad_touch_enabled(self) -> bool:
        pass
    def set_dpad_touch_enabled(self, dpad_touch_enabled: bool) -> None:
        pass

    def get_dpad_touch_increment(self) -> int:
        pass
    def set_dpad_touch_increment(self, dpad_touch_increment: int) -> None:
        pass

    def get_dpad_touch_shortcut1(self) -> int:
        pass
    def set_dpad_touch_shortcut1(self, dpad_touch_shortcut1: int) -> None:
        pass

    def get_dpad_touch_shortcut2(self) -> int:
        pass
    def set_dpad_touch_shortcut2(self, dpad_touch_shortcut2: int) -> None:
        pass

    def get_dpad_touch_shortcut3(self) -> int:
        pass
    def set_dpad_touch_shortcut3(self, dpad_touch_shortcut3: int) -> None:
        pass

    def get_dpad_touch_shortcut4(self) -> int:
        pass
    def set_dpad_touch_shortcut4(self, dpad_touch_shortcut4: int) -> None:
        pass

    def get_psn_account_id(self) -> str:
        pass
    def set_psn_account_id(self, psn_account_id: str) -> None:
        pass

    def get_video_profile_local_ps4(self) -> ChiakiConnectVideoProfile:
        pass
    def get_video_profile_remote_ps4(self) -> ChiakiConnectVideoProfile:
        pass
    def get_video_profile_local_ps5(self) -> ChiakiConnectVideoProfile:
        pass
    def get_video_profile_remote_ps5(self) -> ChiakiConnectVideoProfile:
        pass

    @staticmethod
    def get_chiaki_controller_button_name(chiaki_button: int) -> str:
        pass
    def set_controller_button_mapping(self, chiaki_button: int, key: int) -> None:
        pass
    def get_controller_mapping(self) -> Dict[int, int]:
        pass
    def get_controller_mapping_for_decoding(self) -> Dict[int, int]:
        pass

    def get_registered_host_registered(self, mac: HostMAC) -> bool:
        pass
    def get_manual_hosts(self) -> List[ManualHost]:
        pass

    #std::function<void()> RegisteredHostsUpdated;
    #		std::function<void()> HiddenHostsUpdated;
    #		std::function<void()> ManualHostsUpdated;
    #		std::function<void()> ControllerMappingsUpdated;
    #		std::function<void()> CurrentProfileChanged;
    #		std::function<void()> ProfilesUpdated;
    #		std::function<void()> PlaceboSettingsUpdated;

    def __repr__(self) -> str:
        pass

# #endif
####################    </generated_from:settings.h>    ####################

# </litgen_stub_settings> // Autogenerated code end!

# <litgen_stub_discovery> // Autogenerated code below! Do not edit!
####################    <generated_from:host.h>    ####################
# SPDX-License-Identifier: LicenseRef-AGPL-3.0-only-OpenSSL

# #ifndef CHIAKI_PY_HOST_H
#


class HostMAC:
    """ A console's 6-byte Ethernet MAC address, as used to identify a registered/discovered host."""
    def get_mac(self) -> int:
        pass

    # The MAC address as a hex string.
    def to_string(self) -> str:
        pass
    def get_value(self) -> int:
        pass

    def __str__(self) -> str:
        pass





# #endif
####################    </generated_from:host.h>    ####################


####################    <generated_from:discovery_manager.h>    ####################
# #ifndef CHIAKI_PY_DISCOVERYMANAGER_H
#




class DiscoveryHost:
    """ One console found by DiscoveryManager's broadcast discovery, or filled in by hand to
     register a manual one. `ps5`, `host_addr` and `state` (whether it's awake or in standby)
     are the fields most callers need; the rest mirrors what the console's discovery reply reports.
    """
    ps5: bool
    state: DiscoveryHostState
    target: Target
    host_request_port: int

    host_addr: str
    system_version: str
    device_discovery_protocol_version: str
    host_name: str
    host_type: str
    host_id: str
    running_app_titleid: str
    running_app_name: str

    def get_host_mac(self) -> HostMAC:
        """ The host's MAC address, parsed from host_id."""
        pass
    def __init__(self) -> None:
        """Autogenerated default constructor"""
        pass

class DiscoveryManager:
    """ Broadcasts for PS4/PS5 hosts on the local network (IPv4 and IPv6) in the background and keeps
     track of what answered. `chiaki_py.discover_hosts()` wraps the start/wait/collect/stop sequence
     this class otherwise requires driving by hand.
    """
    def __init__(self) -> None:
        pass

    def set_active(self, active: bool) -> None:
        """ Start or stop broadcasting. Starting re-inits the discovery sockets if they were not
         already active; stopping tears them down and clears the discovered host list.
        """
        pass

    def send_wakeup(self, host: str, regist_key: str, ps5: bool) -> None:
        """ Send a wakeup packet to `host` (a registration's `regist_key`, hex-encoded) so a console
         in standby powers on. Raises ValueError if `regist_key` isn't hex, and RuntimeError if it is
         too long or sending fails.
        """
        pass

    def get_active(self) -> bool:
        """ Whether broadcast discovery is currently running."""
        pass

    def get_hosts(self) -> List[DiscoveryHost]:
        """ The hosts the last broadcast round found. Empty until set_active(True) has had time to hear back."""
        pass

    def discovery_service_hosts(self, hosts: List[DiscoveryHost]) -> None:
        """ Replace the broadcast-discovered host list wholesale. Called internally as broadcast replies
         come in; not normally needed from Python.
        """
        pass

    def hosts_updated(self) -> None:
        pass

# #endif
####################    </generated_from:discovery_manager.h>    ####################

# </litgen_stub_discovery> // Autogenerated code end!

# <litgen_stub_audio> // Autogenerated code below! Do not edit!
####################    <generated_from:audio_handler.h>    ####################
# #ifndef CHIAKI_PY_AUDIO_HANDLER_H
#




class AudioHandler:
    """ The queue of a ChiakiPySession's decoded audio (interleaved int16 PCM), as returned by
     ChiakiPySession.get_audio_handler(). Every read removes the frames it returns, so use one
     consumer only: get_frame(), an AudioOutput or chiaki_py.AudioSink.
    """

    def queue_frame(self, buf: int, samples_count: int) -> None:
        pass

    def get_frame(self, max_frames: int = 0) -> np.ndarray:
        """ Remove and return up to max_frames queued audio frames (0 = all) as an int16 array of shape
         (frames, channels), or of shape (0, 0) if none are queued.
        """
        pass

    def read_frames(self, out: int, max_frames: int) -> int:
        pass

    def get_audio_queued_frames(self) -> int:
        """ The number of audio frames waiting in the queue."""
        pass

    def clear_audio_queue(self) -> None:
        """ Drop every queued audio frame."""
        pass

    def get_audio_queue_max_frames(self) -> int:
        """ The queue capacity in frames; the oldest frames are dropped beyond it."""
        pass

    def set_audio_queue_max_frames(self, max_frames: int) -> None:
        """ Set the queue capacity in frames (0 = 3x the audio buffer size from Settings)."""
        pass

    def get_audio_channels(self) -> int:
        """ The number of audio channels; 0 until the first audio frame arrived."""
        pass

    def get_audio_rate(self) -> int:
        """ The audio sample rate in Hz; 0 until the first audio frame arrived."""
        pass


# #endif
####################    </generated_from:audio_handler.h>    ####################


####################    <generated_from:audio_output.h>    ####################
# #ifndef CHIAKI_PY_AUDIO_OUTPUT_H
#



class AudioOutput:
    """ Plays a session's audio on an SDL output device. SDL's audio thread takes the frames straight
     off the session's AudioHandler queue, without the GIL, so don't read that queue anywhere else
     while it is open. chiaki_py.AudioSink wraps it.

     SDL calls back into C++ for exactly as many frames as the device needs, so playback never waits
     for the GIL. SDL loads the platform's audio backend (WASAPI, CoreAudio, PulseAudio/PipeWire,
     ALSA) at runtime, so nothing beyond the SDL library bundled with the module is needed.
    """

    def open(self, device_name: str = "") -> None:
        """ Open the output device (a name from get_devices(), '' = the system default) at the session's audio
         rate and channel count and start playing. Raises RuntimeError before the first audio frame arrived,
         or if the device can't be opened.
        """
        pass

    def close(self) -> None:
        """ Stop playing and close the device. Does nothing if it isn't open."""
        pass

    def is_open(self) -> bool:
        """ Whether the device is open."""
        pass

    @staticmethod
    def get_devices() -> List[str]:
        """ Names of the available audio output devices."""
        pass


    def __init__(self, session: ChiakiPySession) -> None:
        pass

# #endif
####################    </generated_from:audio_output.h>    ####################

# </litgen_stub_audio> // Autogenerated code end!

# <litgen_stub_session> // Autogenerated code below! Do not edit!
####################    <generated_from:chiakipysession.h>    ####################
# SPDX-License-Identifier: LicenseRef-AGPL-3.0-only-OpenSSL

# #ifndef CHIAKI_PY_SESSION_H
#








class ChiakiPySessionConnectInfo:
    """ Everything ChiakiPySession needs to open a connection to an already-registered console.
     Built from the registration a prior Backend.register_host() produced (`host`, `nickname`,
     `regist_key`, `morning` i.e. the RP key, `target`) plus `settings`; the pythonic
     `chiaki_py.Session` builds one of these from a `HostRegistration` when it is created.
    """

    @overload
    def __init__(self) -> None:
        pass
    @overload
    def __init__(
        self,
        settings: Settings,
        target: Target,
        host: str,
        nickname: str,
        regist_key: str,
        morning: bytes,
        initial_login_pin: str,
        duid: str,
        auto_regist: bool,
        fullscreen: bool,
        zoom: bool,
        stretch: bool
        ) -> None:
        pass

class ChiakiPySession:
    """ A live or about-to-be-started connection to a console: start()/stop() it, feed it
     controller/motion input with the press_*/release_*/set_* methods, and pull decoded video
     through a FrameHandler built around it (see FrameHandler.get_frame() and the CpuFrameHandler/
     CudaFrameHandler/VulkanFrameHandler subclasses). The on_*() methods each return an event
     source frames/state changes can be subscribed to. Usually built and driven indirectly, via
     chiaki_py.Session, rather than used directly.
    """
    def __init__(self, connect_info: ChiakiPySessionConnectInfo) -> None:
        pass

    def is_connected(self) -> bool:
        """ Whether the session is connected."""
        pass
    def is_connecting(self) -> bool:
        """ Whether the session is connecting."""
        pass

    def get_video_profile(self) -> ChiakiConnectVideoProfile:
        """ The stream's video profile (width, height, max_fps, bitrate, codec): the requested one until the
         console answers, then the negotiated one. Known before the first frame arrives.
        """
        pass

    def get_audio_handler(self) -> AudioHandler:
        """ The AudioHandler queueing the session's decoded audio."""
        pass

    def start(self) -> None:
        """ Start the stream session."""
        pass
    def stop(self) -> None:
        """ Stop the stream session."""
        pass
    def go_to_bed(self) -> None:
        """ Put the console into rest mode."""
        pass
    def set_login_pin(self, pin: str) -> None:
        """ Answer the console's login PIN request."""
        pass
    def go_home(self) -> None:
        """ Go to the console's home screen."""
        pass

    def get_host(self) -> str:
        """ The console's address."""
        pass
    def get_connected(self) -> bool:
        pass
    def get_measured_bitrate(self) -> float:
        """ The measured bitrate in Mbit/s."""
        pass
    def get_average_packet_loss(self) -> float:
        """ The average packet loss, 0 to 1."""
        pass
    def get_muted(self) -> bool:
        """ Whether the microphone is muted."""
        pass
    def set_audio_volume(self, volume: int) -> None:
        """ Stored only: playback does not apply it yet."""
        pass
    def get_cant_display(self) -> bool:
        """ Whether the console refused to stream what is on screen (e.g. HDCP-protected video)."""
        pass
    def connect_psn_connection(self, duid: str, ps5: bool) -> ChiakiErrorCode:
        pass
    def cancel_psn_connection(self, stop_thread: bool) -> None:
        pass

    def get_chiaki_log(self) -> ChiakiLog:
        pass
    def get_controllers(self) -> std.list[Controller ]:
        pass
    def get_ffmpeg_decoder(self) -> FfmpegDecoder:
        """ The FFmpeg decoder."""
        pass

    def has_hardware_decoder(self) -> bool:
        """ Whether the video decoder is hardware-accelerated, i.e. CudaFrameHandler/VulkanFrameHandler can return frames."""
        pass

    def hardware_decoder_type(self) -> str:
        """ Type of hardware decoder in use ('vulkan', 'cuda', 'd3d11va', ...), or '' if decoding on the CPU."""
        pass

    def on_audio_frame_available(self) -> BoolEventSource:
        """ Fires whenever decoded audio was queued."""
        pass
    def on_frame_available(self) -> BoolEventSource:
        """ Fires whenever a decoded video frame is ready."""
        pass
    def on_session_quit(self) -> ChiakiQuitReasonEventSource:
        """ Fires with the QuitReason when the session ended."""
        pass
    def on_login_pin_requested(self) -> BoolEventSource:
        """ Fires when the console asks for its login PIN, see set_login_pin()."""
        pass
    def on_data_holepunch_progress(self) -> BoolEventSource:
        """ Fires as a PSN (holepunch) connection progresses."""
        pass
    def on_auto_regist_succeeded(self) -> RegisteredHostEventSource:
        """ Fires with the RegisteredHost once auto-registration succeeded."""
        pass
    def on_nickname_received(self) -> StringEventSource:
        """ Fires with the console's nickname once it is known."""
        pass
    def on_connected_changed(self) -> BoolEventSource:
        """ Fires when is_connected() changes."""
        pass
    def on_measured_bitrate_changed(self) -> DoubleEventSource:
        """ Fires when get_measured_bitrate() changes."""
        pass
    def on_average_packet_loss_changed(self) -> DoubleEventSource:
        """ Fires when get_average_packet_loss() changes."""
        pass
    def on_cant_display_changed(self) -> BoolEventSource:
        """ Fires when get_cant_display() changes."""
        pass

    def press_cross(self) -> None:
        """ Press the cross button."""
        pass
    def release_cross(self) -> None:
        """ Release the cross button."""
        pass

    def press_circle(self) -> None:
        """ Press the circle button."""
        pass
    def release_circle(self) -> None:
        """ Release the circle button."""
        pass

    def press_square(self) -> None:
        """ Press the square button."""
        pass
    def release_square(self) -> None:
        """ Release the square button."""
        pass

    def press_triangle(self) -> None:
        """ Press the triangle button."""
        pass
    def release_triangle(self) -> None:
        """ Release the triangle button."""
        pass

    def press_left(self) -> None:
        """ Press the left button."""
        pass
    def release_left(self) -> None:
        """ Release the left button."""
        pass

    def press_right(self) -> None:
        """ Press the right button."""
        pass
    def release_right(self) -> None:
        """ Release the right button."""
        pass

    def press_up(self) -> None:
        """ Press the up button."""
        pass
    def release_up(self) -> None:
        """ Release the up button."""
        pass

    def press_down(self) -> None:
        """ Press the down button."""
        pass
    def release_down(self) -> None:
        """ Release the down button."""
        pass

    def press_l1(self) -> None:
        """ Press the L1 button."""
        pass
    def release_l1(self) -> None:
        """ Release the L1 button."""
        pass

    def press_r1(self) -> None:
        """ Press the R1 button."""
        pass
    def release_r1(self) -> None:
        """ Release the R1 button."""
        pass

    def press_l3(self) -> None:
        """ Press the L3 button."""
        pass
    def release_l3(self) -> None:
        """ Release the L3 button."""
        pass

    def press_r3(self) -> None:
        """ Press the R3 button."""
        pass
    def release_r3(self) -> None:
        """ Release the R3 button."""
        pass

    def press_options(self) -> None:
        """ Press the options button."""
        pass
    def release_options(self) -> None:
        """ Release the options button."""
        pass

    def press_create(self) -> None:
        """ Press the create button."""
        pass
    def release_create(self) -> None:
        """ Release the create button."""
        pass

    def press_touchpad(self) -> None:
        """ Press the touchpad button."""
        pass
    def release_touchpad(self) -> None:
        """ Release the touchpad button."""
        pass

    def press_ps(self) -> None:
        """ Press the PS button."""
        pass
    def release_ps(self) -> None:
        """ Release the PS button."""
        pass

    def set_l2(self, state: int) -> None:
        """ Set the L2 trigger state [0, 255]."""
        pass

    def set_r2(self, state: int) -> None:
        """ Set the R2 trigger state [0, 255]."""
        pass

    def set_left_x(self, x: int) -> None:
        """ Set the left stick's x value [-32768, 32767], 0 is centered."""
        pass
    def set_left_y(self, y: int) -> None:
        """ Set the left stick's y value [-32768, 32767], 0 is centered."""
        pass
    def set_left(self, x: int, y: int) -> None:
        """ Set the left stick's x and y values [-32768, 32767], 0 is centered."""
        pass

    def set_right_x(self, x: int) -> None:
        """ Set the right stick's x value [-32768, 32767], 0 is centered."""
        pass
    def set_right_y(self, y: int) -> None:
        """ Set the right stick's y value [-32768, 32767], 0 is centered."""
        pass
    def set_right(self, x: int, y: int) -> None:
        """ Set the right stick's x and y values [-32768, 32767], 0 is centered."""
        pass

    def set_accelerometer_x(self, x: float) -> None:
        """ Set the accelerometer x value in g [-5, 5] (at rest: x=0, y=1, z=0)."""
        pass
    def set_accelerometer_y(self, y: float) -> None:
        """ Set the accelerometer y value in g [-5, 5] (at rest: x=0, y=1, z=0)."""
        pass
    def set_accelerometer_z(self, z: float) -> None:
        """ Set the accelerometer z value in g [-5, 5] (at rest: x=0, y=1, z=0)."""
        pass
    def set_accelerometer(self, x: float, y: float, z: float) -> None:
        """ Set the accelerometer x, y and z values in g [-5, 5] (at rest: 0, 1, 0)."""
        pass

    def set_gyroscope_x(self, x: float) -> None:
        """ Set the gyroscope x value in rad/s [-30, 30] (at rest: 0)."""
        pass
    def set_gyroscope_y(self, y: float) -> None:
        """ Set the gyroscope y value in rad/s [-30, 30] (at rest: 0)."""
        pass
    def set_gyroscope_z(self, z: float) -> None:
        """ Set the gyroscope z value in rad/s [-30, 30] (at rest: 0)."""
        pass
    def set_gyroscope(self, x: float, y: float, z: float) -> None:
        """ Set the gyroscope x, y and z values in rad/s [-30, 30] (at rest: 0)."""
        pass

    def set_orientation_x(self, x: float) -> None:
        """ Set the orientation quaternion's x component [-1, 1] (at rest: x=y=z=0, w=1)."""
        pass
    def set_orientation_y(self, y: float) -> None:
        """ Set the orientation quaternion's y component [-1, 1] (at rest: x=y=z=0, w=1)."""
        pass
    def set_orientation_z(self, z: float) -> None:
        """ Set the orientation quaternion's z component [-1, 1] (at rest: x=y=z=0, w=1)."""
        pass
    def set_orientation_w(self, w: float) -> None:
        """ Set the orientation quaternion's w component [-1, 1] (at rest: x=y=z=0, w=1)."""
        pass
    def set_orientation(self, x: float, y: float, z: float, w: float) -> None:
        """ Set the orientation as a unit quaternion (x, y, z, w) (at rest: 0, 0, 0, 1)."""
        pass


    def send_feedback_state(self) -> None:
        """ Send the current controller state to the console. The press_*/release_*/set_* methods do this themselves."""
        pass

# #endif
####################    </generated_from:chiakipysession.h>    ####################

# </litgen_stub_session> // Autogenerated code end!

# <litgen_stub_frame_handler> // Autogenerated code below! Do not edit!
####################    <generated_from:frame_handler.h>    ####################
# #ifndef CHIAKI_PY_FRAME_HANDLER_H
#






class VulkanFrame:
    """ A decoded video frame still resident in GPU memory. Keeps the decoder's frame pool slot and
     device alive until dropped, so release it promptly. The integers are raw handles for interop;
     what they point to depends on hw_type ('vulkan': data[0] is an AVVkFrame*, 'cuda': one device
     pointer per plane, 'd3d11va': data[0] is an ID3D11Texture2D* and data[1] its array slice).
    """
    # Presentation time in seconds.
    pts: float = 0.0      # (read-only)
    # Frame duration in seconds.
    duration: float = 0.0 # (read-only)


    def reset(self, new_frame: AVFrame, new_pts: float, new_duration: float) -> None:
        pass

    def require_frame(self) -> None:
        """ Throws if `frame` is null (a default-constructed VulkanFrame that nothing has reset() into yet):
         every accessor below needs this, since dereferencing a null AVFrame* would otherwise segfault
         the whole interpreter instead of raising a catchable Python exception.
        """
        pass

    def frames_ctx(self) -> AVHWFramesContext:
        pass

    @staticmethod
    def format_name(format: int) -> str:
        pass

    def hw_type(self) -> str:
        pass
    def format(self) -> str:
        pass
    def sw_format(self) -> str:
        pass

    def data(self) -> List[int]:
        pass

    def linesize(self) -> List[int]:
        pass

    def device_hwctx(self) -> int:
        pass

    @staticmethod
    def upload_nv12(
        stream_session: ChiakiPySession,
        nv12: np.ndarray,
        visible_width: Optional[int] = None,
        visible_height: Optional[int] = None
        ) -> VulkanFrame:
        """ Upload an NV12 picture from system memory - a C-contiguous uint8 array of shape
         (height * 3 / 2, width): the luma rows, then the interleaved chroma rows - into a new
         VulkanFrame on the session's Vulkan hardware device (RuntimeError if it does not use one),
         as the decoder would have produced it. The frame shows only the top left
         visible_width x visible_height pixels if given, like a decoded picture that is smaller
         than the image it is stored in. For trying out consumers of VulkanFrames, such as
         VulkanRenderer, without a console.
        """
        pass

    @staticmethod
    def black(stream_session: ChiakiPySession, width: int, height: int) -> VulkanFrame:
        """ A new all-black width x height VulkanFrame on the session's Vulkan hardware device
         (RuntimeError if it does not use one), e.g. as a placeholder picture. Unlike
         VulkanFrameHandler.empty_frame(), which holds no frame and does no GPU work.
        """
        pass

    @property
    def hw_type(self) -> str:
        """Hardware decoder type, e.g. 'vulkan', 'cuda', 'd3d11va'."""
        pass
    @property
    def format(self) -> str:
        """Pixel format of the frame itself, e.g. 'vulkan', 'cuda', 'd3d11'."""
        pass
    @property
    def sw_format(self) -> str:
        """Underlying pixel layout on the GPU, e.g. 'nv12' or 'p010le'."""
        pass
    @property
    def width(self) -> int:
        """Width in pixels. Raises RuntimeError while the frame holds no decoded frame yet."""
        pass
    @property
    def height(self) -> int:
        """Height in pixels. Raises RuntimeError while the frame holds no decoded frame yet."""
        pass
    @property
    def data(self) -> List[int]:
        """Raw per-plane pointers / handles (integers)."""
        pass
    @property
    def linesize(self) -> List[int]:
        """Row stride in bytes for each entry of `data`."""
        pass
    @property
    def device_hwctx(self) -> int:
        """Address of the hardware device context struct (AVVulkanDeviceContext*, AVCUDADeviceContext*, ...) the frame lives on."""
        pass




class FrameHandler:
    """ Base class of the frame handlers, which pull decoded frames out of a ChiakiPySession in
     different forms (CpuFrameHandler, CudaFrameHandler, VulkanFrameHandler). Not instantiable itself.
    """

    def get_frame(self, out: Any = None) -> Any:
        """ Pull the next decoded video frame, or None if none was available yet. What is returned, and
         what `out` may be, depends on the subclass. Raises RuntimeError on decoding failure.
        """
        pass

    @staticmethod
    def empty_frame(width: int = 0, height: int = 0) -> Any:
        """ Not implemented on the base class; call empty_frame() on a concrete subclass instead.
         (Static, so not overridable: each subclass hides it with an empty_frame() of its own, returning
         the empty buffer/frame that its own get_frame() knows how to fill.)
        """
        pass


class CpuFrameHandler(FrameHandler):
    """ Decodes and converts frames to RGB entirely on the CPU. Works with any decoder, needs no
     hardware decoder configured, and is the default FrameHandler `chiaki_py.Session` uses.
    """

    def get_frame(self, out: Any = None) -> Any:
        """ Pull the next decoded video frame as a (height, width, 3) uint8 RGB array, or None if
         none was available yet. If `out` is given it must already have the frame's exact shape
         (C-contiguous, uint8, writable); the frame is written into it and `out` is returned,
         otherwise a new array is allocated. Raises RuntimeError on decoding failure and
         TypeError/ValueError for an unusable `out`.
        """
        pass

    @staticmethod
    def empty_frame(width: int, height: int) -> np.ndarray:
        """ A (height, width, 3) uint8 numpy array, ready to be reused as `out` for get_frame() of frames
         of this size.
        """
        pass


    def __init__(self, stream_session: ChiakiPySession) -> None:
        pass

class CudaFrameHandler(FrameHandler):
    """ Converts decoded frames to RGB on the GPU with CUDA and returns them as a CuPy (or PyTorch)
     array, without a round trip through system memory. Requires an NVIDIA GPU and
     Settings.set_hardware_decoder('cuda') before connecting, which chiaki_py.Session does itself
     for frame_handler_cls=CudaFrameHandler.
    """

    def get_frame(self, out: Any = None) -> Any:
        """ Pull the next decoded video frame on the GPU as a (height, width, 3) uint8 RGB CuPy array,
         converted on the GPU, or None if none was available yet. If `out` is given - a writable
         uint8 CUDA array such as a torch tensor or cupy array, exposing __cuda_array_interface__,
         shaped (height, width, 3) and C-contiguous ('channels last'), or (3, height, width) as a
         transpose/permute view over that same interleaved memory ('channels first', e.g. from
         empty_frame(channels_last=False)) - the frame is converted into it instead and `out` is
         returned; otherwise a new CuPy array is allocated. The conversion has finished when this
         returns. Requires hardware_decoder='cuda' (RuntimeError otherwise); a bad `out` raises
         TypeError/ValueError.
        """
        pass

    @staticmethod
    def empty_frame(
        width: int,
        height: int,
        backend: str = "cupy",
        channels_last: bool = True
        ) -> Any:
        """ A uint8 CUDA array, ready to be reused as `out` for get_frame() of frames of this size.
         `backend` is 'cupy' (default) or 'torch', selecting what allocates it - torch requires a
         CUDA build of PyTorch and returns a tensor on 'cuda'. With `channels_last` true (default)
         it is shaped (height, width, 3); with it false, (3, height, width) instead - a
         transpose/permute view of that same interleaved RGB memory, for a model that wants CHW,
         with no extra copy.
        """
        pass

    def __init__(self, stream_session: ChiakiPySession) -> None:
        pass

class VulkanFrameHandler(FrameHandler):
    """ Hands out frames as VulkanFrame objects that stay resident on the GPU device the decoder
     decoded them on - no conversion, no copy. Normally used with Settings.set_hardware_decoder('vulkan')
     (chiaki_py.Session sets it for frame_handler_cls=VulkanFrameHandler), which VulkanRenderer needs to
     draw them, e.g. via chiaki_py.gui.VulkanVideoWidget; with another hardware decoder the frames are
     that decoder's (see VulkanFrame.hw_type).
    """

    def get_frame(self, out: Any = None) -> Any:
        """ Pull the next decoded video frame without leaving GPU memory. Returns a VulkanFrame, or None
         if none was available yet. If `out` is a VulkanFrame it takes over the new frame (releasing
         the one it held) and is returned instead of a new VulkanFrame being created. Raises
         RuntimeError if the session doesn't use a hardware decoder and TypeError if `out` isn't a VulkanFrame.
        """
        pass

    @staticmethod
    def empty_frame(width: int = 0, height: int = 0) -> VulkanFrame:
        """ An empty VulkanFrame holding no decoded frame yet, ready to be reused as `out` for get_frame().
         `width`/`height` are accepted for a uniform empty_frame(width, height) signature but otherwise
         unused, since a VulkanFrame takes on whatever size the next decoded frame actually has. Does no
         GPU work, unlike VulkanFrame.black(): use that directly if you need a real placeholder picture
         and can guarantee it won't run concurrently with the hardware decoder's own Vulkan submissions.
        """
        pass

    def __init__(self, stream_session: ChiakiPySession) -> None:
        pass

# #endif
####################    </generated_from:frame_handler.h>    ####################

# </litgen_stub_frame_handler> // Autogenerated code end!

# <litgen_stub_vulkan_renderer> // Autogenerated code below! Do not edit!
####################    <generated_from:vulkan_renderer.h>    ####################
# #ifndef CHIAKI_PY_VULKAN_RENDERER_H
#



class VulkanWindowSystem(enum.IntEnum):
    """ The kind of native window a VulkanRenderer draws into, which decides what its `window` and `display` are."""
    Default = enum.auto() # (= 0)  # Win32 on Windows, X11 elsewhere
    Win32 = enum.auto()   # (= 1)  # window: an HWND; display: unused
    X11 = enum.auto()     # (= 2)  # window: an X11 Window id (what Qt's winId() is on X11); display: an Xlib Display*, or 0 to open a connection of its own
    Wayland = enum.auto() # (= 3)  # window: a wl_surface*; display: the wl_display* it belongs to (both from the toolkit, e.g. GLFW's or SDL's)

class VulkanRenderer:
    """ Draws VulkanFrames of the Vulkan hardware decoder into a native window without them leaving the
     GPU: libplacebo converts the frames' NV12/P010 planes to RGB (SDR or HDR), scales them and presents
     them on the same Vulkan device the decoder decodes on. Windows (Win32) and Linux (X11 and Wayland).

     The Vulkan device the decoder decodes on (see the ChiakiPySession constructor, which has libplacebo create
     it) is also the one drawn on, so a decoded frame is used where it is: libplacebo samples its NV12/P010
     planes, converts them to RGB with the frame's own colour space (SDR or HDR), scales them to the window and
     presents the result on the window's swapchain. Nothing is copied.

     All calls must come from one thread (not necessarily the GUI thread - the Python binding uses a
     dedicated thread of its own, since a call here can block for a while - see VulkanRenderThread),
     except set_size(), and close() before the window is destroyed.
    """

    def render(self, frame: VulkanFrame) -> None:
        """ Draw `frame`, a VulkanFrame from the Vulkan decoder, scaled to fit the window with its aspect
         ratio kept, and present it. Does nothing while the window has no area (is minimised), or on Wayland
         before set_size() was called. Returns once the drawing is submitted, not finished; the GPU is waited
         for when the next frame needs it.
        """
        pass

    def set_size(self, width: int, height: int) -> None:
        """ The size in pixels to draw at, for window systems that leave it to the renderer: Wayland, where a surface is
         as big as what is drawn into it. Call it whenever the window's size changes, from any thread. Elsewhere the
         window's own size is used and this is ignored.
        """
        pass

    def set_overlay(self, rgba: int, width: int, height: int, margin: int) -> None:
        """ Shows `rgba` - width x height pixels, 8 bit RGBA rows with premultiplied alpha, tightly packed - on top of the
         video, in the top-right corner of the window, `margin` pixels from its edges, until it is replaced or cleared.
         The image is copied. libplacebo composites it in the same pass that draws the video.
        """
        pass

    def clear_overlay(self) -> None:
        """ Remove the overlay, if there is one."""
        pass

    def close(self) -> None:
        """ Wait for the GPU to be done with everything drawn so far and free everything. Call before the
         window is destroyed; safe to call twice.
        """
        pass

    @staticmethod
    def is_supported() -> bool:
        """ Whether this build can draw into windows of this platform (Windows, and Linux if it was built with libplacebo)."""
        pass


    def __init__(self, stream_session: ChiakiPySession, window: int, display: int = 0, window_system: VulkanWindowSystem = VulkanWindowSystem.Default) -> None:
        """Draw into the native window `window`, of the connection `display`, as `window_system` says: an HWND on Windows; an X11 Window id (e.g. Qt's winId()) and an Xlib Display* or 0 on X11; a wl_surface* and its wl_display* on Wayland. The session must use the Vulkan hardware decoder (Settings.set_hardware_decoder('vulkan')); raises RuntimeError otherwise, or if the window can't be drawn into."""
        pass
    def set_overlay(self, rgba: np.ndarray, margin: int = 12) -> None:
        """Show `rgba`, a uint8 array of shape (height, width, 4) with premultiplied alpha, on top of the video
        in the top-right corner of the window, `margin` pixels from its edges, until it is replaced or cleared.
        The pixels are copied. libplacebo composites it in the same pass that draws the video, so it is not
        part of the frames, and it stays where it is while the window is resized."""
        pass

# #endif
####################    </generated_from:vulkan_renderer.h>    ####################

# </litgen_stub_vulkan_renderer> // Autogenerated code end!

# <litgen_stub_backend> // Autogenerated code below! Do not edit!
####################    <generated_from:backend.h>    ####################
# #ifndef CHIAKI_PY_BACKEND_H
#




PSN_DEVICES_TRIES = 2
MAX_PSN_RECONNECT_TRIES = 6
PSN_INTERNET_WAIT_SECONDS = 5
WAKEUP_PSN_IGNORE_SECONDS = 10
WAKEUP_WAIT_SECONDS = 25




class RegistResult:
    """ What Backend.register_host() (the blocking variant) returns on success: the same fields as
     RegisteredHost, copied out of the underlying RegistEvent once registration completes.
    """
    type: RegistEventType # (read-only)
    target: Target        # (read-only)
    ap_ssid: str          # (read-only)
    ap_bssid: str         # (read-only)
    ap_key: str           # (read-only)
    ap_name: str          # (read-only)
    # The console's MAC address, as 'aa:bb:cc:dd:ee:ff'.
    server_mac: str       # (read-only)
    server_nickname: str  # (read-only)
    rp_regist_key: str    # (read-only)
    rp_key_type: int      # (read-only)
    console_pin: int      # (read-only)


    @property
    def rp_key(self) -> bytes:
        """The RP key, which ChiakiPySessionConnectInfo takes as `morning`."""
        pass
    def __repr__(self) -> str:
        pass

class PsnConnectState(enum.IntEnum):
    """ Stages of connecting to a console over PSN (remote play over the internet, via holepunching)
     rather than the local network. Exported for forward compatibility; no bound method currently
     returns one, since the PSN remote-connect path isn't wired up yet.
    """
    NotStarted = enum.auto()                      # (= 0)
    WaitingForInternet = enum.auto()              # (= 1)
    InitiatingConnection = enum.auto()            # (= 2)
    LinkingConsole = enum.auto()                  # (= 3)
    RegisteringConsole = enum.auto()              # (= 4)
    RegistrationFinished = enum.auto()            # (= 5)
    DataConnectionStart = enum.auto()             # (= 6)
    DataConnectionFinished = enum.auto()          # (= 7)
    ConnectFailed = enum.auto()                   # (= 8)
    ConnectFailedStart = enum.auto()              # (= 9)
    ConnectFailedConsoleUnreachable = enum.auto() # (= 10)

class Backend:
    """ Registers with a console: the one-time PIN pairing that gets back the registration key
     ChiakiPySession later needs to connect. `chiaki_py.register_host()` wraps register_host() with
     a pythonic result type (HostRegistration) and is the easier way to call this from Python.
    """
    def __init__(self) -> None:
        pass


    def register_host_async(
        self,
        host: str,
        psn_id: str,
        pin: str,
        cpin: str,
        broadcast: bool,
        target: Target
        ) -> RegistEventSource:
        """ Start registering with `host` and return a RegistEventSource that reports the outcome
         once subscribed to, instead of blocking. `psn_id` is the PSN account-ID (base64) for a
         PS5 or a PS4 in 'PS4 8.0' mode, or the online ID for an older PS4; `pin` is the one-time
         PIN shown on the console's registration screen, `cpin` its login PIN if it has one
         (otherwise empty). Raises RuntimeError immediately if `psn_id` is not valid base64 of the
         expected length for a PS5/PS4-8.0 `target`.
        """
        pass

    def register_host(
        self,
        host: str,
        psn_id: str,
        pin: str,
        cpin: str,
        broadcast: bool,
        target: Target
        ) -> RegistResult:
        """ Like register_host_async(), but blocks until registration finishes and returns the
         RegistResult directly, or raises RuntimeError on failure.
        """
        pass


# #endif ####################    </generated_from:backend.h>    ####################

# </litgen_stub_backend> // Autogenerated code end!
