#ifndef CHIAKI_PY_BINDINGS_PYDEF_H
#define CHIAKI_PY_BINDINGS_PYDEF_H

#include <pybind11/pybind11.h>
#include <pybind11/functional.h>
#include <pybind11/numpy.h>
#include <pybind11/stl.h>

namespace py = pybind11;

// Each adds a part of the chiaki_py module to `m`; module.cpp calls them in order.
// Written by hand:
void py_init_chiaki(py::module_ &m);       // pydef_chiaki.cpp: chiaki's C types, and the `core` submodule
void py_init_event_source(py::module_ &m); // pydef_event_source.cpp: the EventSource<T> instances
// Generated by generate_bindings.py, each from the headers it names:
void py_init_settings(py::module_ &m);
void py_init_discovery(py::module_ &m);
void py_init_audio(py::module_ &m);
void py_init_session(py::module_ &m);
void py_init_frame_handler(py::module_ &m);
void py_init_vulkan_renderer(py::module_ &m);
void py_init_backend(py::module_ &m);

#endif // CHIAKI_PY_BINDINGS_PYDEF_H
