// Bindings generated by generate_bindings.py: edit the headers or the generator, not the code between the markers.

#include "pydef.h"

#include "frame_handler.h"

void py_init_frame_handler(py::module_ &m)
{
    // <litgen_pydef> // Autogenerated code below! Do not edit!
    ////////////////////    <generated_from:frame_handler.h>    ////////////////////
    // #ifndef CHIAKI_PY_FRAME_HANDLER_H
    //


    auto pyClassVulkanFrame =
        py::class_<VulkanFrame>
            (m, "VulkanFrame", " A decoded video frame still resident in GPU memory. Keeps the decoder's frame pool slot and\n device alive until dropped, so release it promptly. The integers are raw handles for interop;\n what they point to depends on hw_type ('vulkan': data[0] is an AVVkFrame*, 'cuda': one device\n pointer per plane, 'd3d11va': data[0] is an ID3D11Texture2D* and data[1] its array slice).")
        .def_readonly("pts", &VulkanFrame::pts, "Presentation time in seconds.")
        .def_readonly("duration", &VulkanFrame::duration, "Frame duration in seconds.")
        .def("reset",
            &VulkanFrame::reset, py::arg("new_frame"), py::arg("new_pts"), py::arg("new_duration"))
        .def("require_frame",
            &VulkanFrame::require_frame, " Throws if `frame` is null (a default-constructed VulkanFrame that nothing has reset() into yet):\n every accessor below needs this, since dereferencing a null AVFrame* would otherwise segfault\n the whole interpreter instead of raising a catchable Python exception.")
        .def("frames_ctx",
            &VulkanFrame::frames_ctx, py::return_value_policy::reference)
        .def_static("format_name",
            &VulkanFrame::format_name, py::arg("format"))
        .def("hw_type",
            &VulkanFrame::hw_type)
        .def("format",
            &VulkanFrame::format)
        .def("sw_format",
            &VulkanFrame::sw_format)
        .def("data",
            &VulkanFrame::data)
        .def("linesize",
            &VulkanFrame::linesize)
        .def("device_hwctx",
            &VulkanFrame::device_hwctx)
        .def_static("upload_nv12",
            &VulkanFrame::upload_nv12,
            py::arg("stream_session"), py::arg("nv12"), py::arg("visible_width") = py::none(), py::arg("visible_height") = py::none(),
            " Upload an NV12 picture from system memory - a C-contiguous uint8 array of shape\n (height * 3 / 2, width): the luma rows, then the interleaved chroma rows - into a new\n VulkanFrame on the session's Vulkan hardware device (RuntimeError if it does not use one),\n as the decoder would have produced it. The frame shows only the top left\n visible_width x visible_height pixels if given, like a decoded picture that is smaller\n than the image it is stored in. For trying out consumers of VulkanFrames, such as\n VulkanRenderer, without a console.")
        .def_static("black",
            &VulkanFrame::black,
            py::arg("stream_session"), py::arg("width"), py::arg("height"),
            " A new all-black width x height VulkanFrame on the session's Vulkan hardware device\n (RuntimeError if it does not use one), e.g. as a placeholder picture. Unlike\n VulkanFrameHandler.empty_frame(), which holds no frame and does no GPU work.")
        ;

    pyClassVulkanFrame.def_property_readonly("hw_type", &VulkanFrame::hw_type, "Hardware decoder type, e.g. 'vulkan', 'cuda', 'd3d11va'.");
    pyClassVulkanFrame.def_property_readonly("format", &VulkanFrame::format, "Pixel format of the frame itself, e.g. 'vulkan', 'cuda', 'd3d11'.");
    pyClassVulkanFrame.def_property_readonly("sw_format", &VulkanFrame::sw_format, "Underlying pixel layout on the GPU, e.g. 'nv12' or 'p010le'.");
    pyClassVulkanFrame.def_property_readonly("width", [](const VulkanFrame &f) { f.require_frame(); return f.frame->width; }, "Width in pixels. Raises RuntimeError while the frame holds no decoded frame yet.");
    pyClassVulkanFrame.def_property_readonly("height", [](const VulkanFrame &f) { f.require_frame(); return f.frame->height; }, "Height in pixels. Raises RuntimeError while the frame holds no decoded frame yet.");
    pyClassVulkanFrame.def_property_readonly("data", &VulkanFrame::data, "Raw per-plane pointers / handles (integers).");
    pyClassVulkanFrame.def_property_readonly("linesize", &VulkanFrame::linesize, "Row stride in bytes for each entry of `data`.");
    pyClassVulkanFrame.def_property_readonly("device_hwctx", &VulkanFrame::device_hwctx, "Address of the hardware device context struct (AVVulkanDeviceContext*, AVCUDADeviceContext*, ...) the frame lives on.");




    auto pyClassFrameHandler =
        py::class_<FrameHandler>
            (m, "FrameHandler", " Base class of the frame handlers, which pull decoded frames out of a ChiakiPySession in\n different forms (CpuFrameHandler, CudaFrameHandler, VulkanFrameHandler). Not instantiable itself.")
        .def("get_frame",
            &FrameHandler::get_frame,
            py::arg("out") = py::none(),
            " Pull the next decoded video frame, or None if none was available yet. What is returned, and\n what `out` may be, depends on the subclass. Raises RuntimeError on decoding failure.")
        .def_static("empty_frame",
            &FrameHandler::empty_frame,
            py::arg("width") = 0, py::arg("height") = 0,
            " Not implemented on the base class; call empty_frame() on a concrete subclass instead.\n (Static, so not overridable: each subclass hides it with an empty_frame() of its own, returning\n the empty buffer/frame that its own get_frame() knows how to fill.)")
        ;


    auto pyClassCpuFrameHandler =
        py::class_<CpuFrameHandler, FrameHandler>
            (m, "CpuFrameHandler", " Decodes and converts frames to RGB entirely on the CPU. Works with any decoder, needs no\n hardware decoder configured, and is the default FrameHandler `chiaki_py.Session` uses.")
        .def("get_frame",
            &CpuFrameHandler::get_frame,
            py::arg("out") = py::none(),
            " Pull the next decoded video frame as a (height, width, 3) uint8 RGB array, or None if\n none was available yet. If `out` is given it must already have the frame's exact shape\n (C-contiguous, uint8, writable); the frame is written into it and `out` is returned,\n otherwise a new array is allocated. Raises RuntimeError on decoding failure and\n TypeError/ValueError for an unusable `out`.")
        .def_static("empty_frame",
            &CpuFrameHandler::empty_frame,
            py::arg("width"), py::arg("height"),
            " A (height, width, 3) uint8 numpy array, ready to be reused as `out` for get_frame() of frames\n of this size.")
        ;

    pyClassCpuFrameHandler.def(py::init<ChiakiPySession *>(), py::arg("stream_session"), py::keep_alive<1, 2>());




    auto pyClassCudaFrameHandler =
        py::class_<CudaFrameHandler, FrameHandler>
            (m, "CudaFrameHandler", " Converts decoded frames to RGB on the GPU with CUDA and returns them as a CuPy (or PyTorch)\n array, without a round trip through system memory. Requires an NVIDIA GPU and\n Settings.set_hardware_decoder('cuda') before connecting, which chiaki_py.Session does itself\n for frame_handler_cls=CudaFrameHandler.")
        .def("get_frame",
            &CudaFrameHandler::get_frame,
            py::arg("out") = py::none(),
            " Pull the next decoded video frame on the GPU as a (height, width, 3) uint8 RGB CuPy array,\n converted on the GPU, or None if none was available yet. If `out` is given - a writable\n uint8 CUDA array such as a torch tensor or cupy array, exposing __cuda_array_interface__,\n shaped (height, width, 3) and C-contiguous ('channels last'), or (3, height, width) as a\n transpose/permute view over that same interleaved memory ('channels first', e.g. from\n empty_frame(channels_last=False)) - the frame is converted into it instead and `out` is\n returned; otherwise a new CuPy array is allocated. The conversion has finished when this\n returns. Requires hardware_decoder='cuda' (RuntimeError otherwise); a bad `out` raises\n TypeError/ValueError.")
        .def_static("empty_frame",
            &CudaFrameHandler::empty_frame,
            py::arg("width"), py::arg("height"), py::arg("backend") = "cupy", py::arg("channels_last") = true,
            " A uint8 CUDA array, ready to be reused as `out` for get_frame() of frames of this size.\n `backend` is 'cupy' (default) or 'torch', selecting what allocates it - torch requires a\n CUDA build of PyTorch and returns a tensor on 'cuda'. With `channels_last` true (default)\n it is shaped (height, width, 3); with it false, (3, height, width) instead - a\n transpose/permute view of that same interleaved RGB memory, for a model that wants CHW,\n with no extra copy.")
        ;

    pyClassCudaFrameHandler.def(py::init<ChiakiPySession *>(), py::arg("stream_session"), py::keep_alive<1, 2>());




    auto pyClassVulkanFrameHandler =
        py::class_<VulkanFrameHandler, FrameHandler>
            (m, "VulkanFrameHandler", " Hands out frames as VulkanFrame objects that stay resident on the GPU device the decoder\n decoded them on - no conversion, no copy. Normally used with Settings.set_hardware_decoder('vulkan')\n (chiaki_py.Session sets it for frame_handler_cls=VulkanFrameHandler), which VulkanRenderer needs to\n draw them, e.g. via chiaki_py.gui.VulkanVideoWidget; with another hardware decoder the frames are\n that decoder's (see VulkanFrame.hw_type).")
        .def("get_frame",
            &VulkanFrameHandler::get_frame,
            py::arg("out") = py::none(),
            " Pull the next decoded video frame without leaving GPU memory. Returns a VulkanFrame, or None\n if none was available yet. If `out` is a VulkanFrame it takes over the new frame (releasing\n the one it held) and is returned instead of a new VulkanFrame being created. Raises\n RuntimeError if the session doesn't use a hardware decoder and TypeError if `out` isn't a VulkanFrame.")
        .def_static("empty_frame",
            &VulkanFrameHandler::empty_frame,
            py::arg("width") = 0, py::arg("height") = 0,
            " An empty VulkanFrame holding no decoded frame yet, ready to be reused as `out` for get_frame().\n `width`/`height` are accepted for a uniform empty_frame(width, height) signature but otherwise\n unused, since a VulkanFrame takes on whatever size the next decoded frame actually has. Does no\n GPU work, unlike VulkanFrame.black(): use that directly if you need a real placeholder picture\n and can guarantee it won't run concurrently with the hardware decoder's own Vulkan submissions.")
        ;

    pyClassVulkanFrameHandler.def(py::init<ChiakiPySession *>(), py::arg("stream_session"), py::keep_alive<1, 2>());


    // #endif
    ////////////////////    </generated_from:frame_handler.h>    ////////////////////

    // </litgen_pydef> // Autogenerated code end
}
