// Bindings generated by generate_bindings.py: edit the headers or the generator, not the code between the markers.

#include "pydef.h"

#include "backend.h"

#include <iomanip>
#include <sstream>

void py_init_backend(py::module_ &m)
{
    // <litgen_pydef> // Autogenerated code below! Do not edit!
    ////////////////////    <generated_from:backend.h>    ////////////////////
    // #ifndef CHIAKI_PY_BACKEND_H
    //
    m.attr("PSN_DEVICES_TRIES") = 2;
    m.attr("MAX_PSN_RECONNECT_TRIES") = 6;
    m.attr("PSN_INTERNET_WAIT_SECONDS") = 5;
    m.attr("WAKEUP_PSN_IGNORE_SECONDS") = 10;
    m.attr("WAKEUP_WAIT_SECONDS") = 25;


    auto pyClassRegistResult =
        py::class_<RegistResult>
            (m, "RegistResult", " What Backend.register_host() (the blocking variant) returns on success: the same fields as\n RegisteredHost, copied out of the underlying RegistEvent once registration completes.")
        .def_readonly("type", &RegistResult::type, "")
        .def_readonly("target", &RegistResult::target, "")
        .def_readonly("ap_ssid", &RegistResult::ap_ssid, "")
        .def_readonly("ap_bssid", &RegistResult::ap_bssid, "")
        .def_readonly("ap_key", &RegistResult::ap_key, "")
        .def_readonly("ap_name", &RegistResult::ap_name, "")
        .def_readonly("server_mac", &RegistResult::server_mac, "")
        .def_readonly("server_nickname", &RegistResult::server_nickname, "")
        .def_readonly("rp_regist_key", &RegistResult::rp_regist_key, "")
        .def_readonly("rp_key_type", &RegistResult::rp_key_type, "")
        .def_readonly("console_pin", &RegistResult::console_pin, "")
        ;

    pyClassRegistResult.def_property_readonly("rp_key", [](const RegistResult &r)
    {
        return py::bytes(reinterpret_cast<const char *>(r.rp_key), sizeof(r.rp_key));
    }, "The RP key, which ChiakiPySessionConnectInfo takes as `morning`.");
    pyClassRegistResult.def("__repr__", [](const RegistResult &r)
    {
        std::ostringstream rp_key;
        for (uint8_t byte : r.rp_key)
            rp_key << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(byte);
        std::ostringstream repr;
        repr << "<RegistResult"
             << " type=" << py::str(py::cast(r.type)).cast<std::string>()
             << " target=" << py::str(py::cast(r.target)).cast<std::string>()
             << " ap_ssid='" << r.ap_ssid << "'"
             << " ap_bssid='" << r.ap_bssid << "'"
             << " ap_key='" << r.ap_key << "'"
             << " ap_name='" << r.ap_name << "'"
             << " server_mac=" << r.server_mac
             << " server_nickname='" << r.server_nickname << "'"
             << " rp_regist_key='" << r.rp_regist_key << "'"
             << " rp_key='" << rp_key.str() << "'"
             << " rp_key_type=" << r.rp_key_type
             << " console_pin=" << r.console_pin
             << ">";
        return repr.str();
    });




    auto pyEnumPsnConnectState =
        py::enum_<PsnConnectState>(m, "PsnConnectState", py::arithmetic(), " Stages of connecting to a console over PSN (remote play over the internet, via holepunching)\n rather than the local network. Exported for forward compatibility; no bound method currently\n returns one, since the PSN remote-connect path isn't wired up yet.")
            .value("NotStarted", PsnConnectState::NotStarted, "")
            .value("WaitingForInternet", PsnConnectState::WaitingForInternet, "")
            .value("InitiatingConnection", PsnConnectState::InitiatingConnection, "")
            .value("LinkingConsole", PsnConnectState::LinkingConsole, "")
            .value("RegisteringConsole", PsnConnectState::RegisteringConsole, "")
            .value("RegistrationFinished", PsnConnectState::RegistrationFinished, "")
            .value("DataConnectionStart", PsnConnectState::DataConnectionStart, "")
            .value("DataConnectionFinished", PsnConnectState::DataConnectionFinished, "")
            .value("ConnectFailed", PsnConnectState::ConnectFailed, "")
            .value("ConnectFailedStart", PsnConnectState::ConnectFailedStart, "")
            .value("ConnectFailedConsoleUnreachable", PsnConnectState::ConnectFailedConsoleUnreachable, "")
        .export_values();


    auto pyClassBackend =
        py::class_<Backend>
            (m, "Backend", " Registers with a console: the one-time PIN pairing that gets back the registration key\n ChiakiPySession later needs to connect. `chiaki_py.register_host()` wraps register_host() with\n a pythonic result type (HostRegistration) and is the easier way to call this from Python.")
        .def(py::init<>())
        .def("register_host_async",
            &Backend::registerHostAsync,
            py::arg("host"), py::arg("psn_id"), py::arg("pin"), py::arg("cpin"), py::arg("broadcast"), py::arg("target"),
            " Start registering with `host` and return a RegistEventSource that reports the outcome\n once subscribed to, instead of blocking. `psn_id` is the PSN account-ID (base64) for a\n PS5 or a PS4 in 'PS4 8.0' mode, or the online ID for an older PS4; `pin` is the one-time\n PIN shown on the console's registration screen, `cpin` its login PIN if it has one\n (otherwise empty). Raises RuntimeError immediately if `psn_id` is not valid base64 of the\n expected length for a PS5/PS4-8.0 `target`.",
            py::return_value_policy::reference)
        .def("register_host",
            &Backend::registerHost,
            py::arg("host"), py::arg("psn_id"), py::arg("pin"), py::arg("cpin"), py::arg("broadcast"), py::arg("target"),
            " Like register_host_async(), but blocks until registration finishes and returns the\n RegistResult directly, or raises RuntimeError on failure.")
        ;
    // #endif
    ////////////////////    </generated_from:backend.h>    ////////////////////

    // </litgen_pydef> // Autogenerated code end
}
