// Bindings generated by generate_bindings.py: edit the headers or the generator, not the code between the markers.

#include "pydef.h"

#include "chiakipysession.h"

void py_init_session(py::module_ &m)
{
    // <litgen_pydef> // Autogenerated code below! Do not edit!
    ////////////////////    <generated_from:chiakipysession.h>    ////////////////////
    // #ifndef CHIAKI_PY_SESSION_H
    //


    auto pyClassChiakiPySessionConnectInfo =
        py::class_<ChiakiPySessionConnectInfo>
            (m, "ChiakiPySessionConnectInfo", " Everything ChiakiPySession needs to open a connection to an already-registered console.\n Built from the registration a prior Backend.register_host() produced (`host`, `nickname`,\n `regist_key`, `morning` i.e. the RP key, `target`) plus `settings`; the pythonic\n `chiaki_py.Session` builds one of these from a `HostRegistration` when it is created.")
        .def(py::init<>())
        .def(py::init<Settings *, ChiakiTarget, std::string, std::string, std::string &, py::bytes, std::string, std::string, bool, bool, bool, bool>(),
            py::arg("settings"), py::arg("target"), py::arg("host"), py::arg("nickname"), py::arg("regist_key"), py::arg("morning"), py::arg("initial_login_pin"), py::arg("duid"), py::arg("auto_regist"), py::arg("fullscreen"), py::arg("zoom"), py::arg("stretch"))
        ;


    auto pyClassChiakiPySession =
        py::class_<ChiakiPySession>
            (m, "ChiakiPySession", " A live or about-to-be-started connection to a console: start()/stop() it, feed it\n controller/motion input with the press_*/release_*/set_* methods, and pull decoded video\n through a FrameHandler built around it (see FrameHandler.get_frame() and the CpuFrameHandler/\n CudaFrameHandler/VulkanFrameHandler subclasses). The on_*() methods each return an event\n source frames/state changes can be subscribed to. Usually built and driven indirectly, via\n chiaki_py.Session, rather than used directly.")
        .def(py::init<const ChiakiPySessionConnectInfo &>(),
            py::arg("connect_info"))
        .def("is_connected",
            &ChiakiPySession::IsConnected, "Whether the session is connected.")
        .def("is_connecting",
            &ChiakiPySession::IsConnecting, "Whether the session is connecting.")
        .def("get_video_profile",
            &ChiakiPySession::GetVideoProfile, " The stream's video profile (width, height, max_fps, bitrate, codec): the requested one until the\n console answers, then the negotiated one. Known before the first frame arrives.")
        .def("get_audio_handler",
            &ChiakiPySession::GetAudioHandler,
            "The AudioHandler queueing the session's decoded audio.",
            py::return_value_policy::reference)
        .def("start",
            &ChiakiPySession::Start, "Start the stream session.")
        .def("stop",
            &ChiakiPySession::Stop, "Stop the stream session.")
        .def("go_to_bed",
            &ChiakiPySession::GoToBed, "Put the console into rest mode.")
        .def("set_login_pin",
            &ChiakiPySession::SetLoginPIN,
            py::arg("pin"),
            "Answer the console's login PIN request.")
        .def("go_home",
            &ChiakiPySession::GoHome, "Go to the console's home screen.")
        .def("get_host",
            &ChiakiPySession::GetHost, "The console's address.")
        .def("get_connected",
            &ChiakiPySession::GetConnected)
        .def("get_measured_bitrate",
            &ChiakiPySession::GetMeasuredBitrate, "The measured bitrate in Mbit/s.")
        .def("get_average_packet_loss",
            &ChiakiPySession::GetAveragePacketLoss, "The average packet loss, 0 to 1.")
        .def("get_muted",
            &ChiakiPySession::GetMuted, "Whether the microphone is muted.")
        .def("set_audio_volume",
            &ChiakiPySession::SetAudioVolume,
            py::arg("volume"),
            "Stored only: playback does not apply it yet.")
        .def("get_cant_display",
            &ChiakiPySession::GetCantDisplay, "Whether the console refused to stream what is on screen (e.g. HDCP-protected video).")
        .def("connect_psn_connection",
            &ChiakiPySession::ConnectPsnConnection, py::arg("duid"), py::arg("ps5"))
        .def("cancel_psn_connection",
            &ChiakiPySession::CancelPsnConnection, py::arg("stop_thread"))
        .def("get_chiaki_log",
            &ChiakiPySession::GetChiakiLog, py::return_value_policy::reference)
        .def("get_controllers",
            &ChiakiPySession::GetControllers)
        .def("get_ffmpeg_decoder",
            &ChiakiPySession::GetFfmpegDecoder,
            "The FFmpeg decoder.",
            py::return_value_policy::reference)
        .def("has_hardware_decoder",
            &ChiakiPySession::HasHardwareDecoder, "Whether the video decoder is hardware-accelerated, i.e. CudaFrameHandler/VulkanFrameHandler can return frames.")
        .def("hardware_decoder_type",
            &ChiakiPySession::HardwareDecoderType, "Type of hardware decoder in use ('vulkan', 'cuda', 'd3d11va', ...), or '' if decoding on the CPU.")
        .def("on_audio_frame_available",
            &ChiakiPySession::OnAudioFrameAvailable,
            "Fires whenever decoded audio was queued.",
            py::return_value_policy::reference)
        .def("on_frame_available",
            &ChiakiPySession::OnFrameAvailable,
            "Fires whenever a decoded video frame is ready.",
            py::return_value_policy::reference)
        .def("on_session_quit",
            &ChiakiPySession::OnSessionQuit,
            "Fires with the QuitReason when the session ended.",
            py::return_value_policy::reference)
        .def("on_login_pin_requested",
            &ChiakiPySession::OnLoginPINRequested,
            "Fires when the console asks for its login PIN, see set_login_pin().",
            py::return_value_policy::reference)
        .def("on_data_holepunch_progress",
            &ChiakiPySession::OnDataHolepunchProgress,
            "Fires as a PSN (holepunch) connection progresses.",
            py::return_value_policy::reference)
        .def("on_auto_regist_succeeded",
            &ChiakiPySession::OnAutoRegistSucceeded,
            "Fires with the RegisteredHost once auto-registration succeeded.",
            py::return_value_policy::reference)
        .def("on_nickname_received",
            &ChiakiPySession::OnNicknameReceived,
            "Fires with the console's nickname once it is known.",
            py::return_value_policy::reference)
        .def("on_connected_changed",
            &ChiakiPySession::OnConnectedChanged,
            "Fires when is_connected() changes.",
            py::return_value_policy::reference)
        .def("on_measured_bitrate_changed",
            &ChiakiPySession::OnMeasuredBitrateChanged,
            "Fires when get_measured_bitrate() changes.",
            py::return_value_policy::reference)
        .def("on_average_packet_loss_changed",
            &ChiakiPySession::OnAveragePacketLossChanged,
            "Fires when get_average_packet_loss() changes.",
            py::return_value_policy::reference)
        .def("on_cant_display_changed",
            &ChiakiPySession::OnCantDisplayChanged,
            "Fires when get_cant_display() changes.",
            py::return_value_policy::reference)
        .def("press_cross",
            &ChiakiPySession::pressCross, "Press the cross button.")
        .def("release_cross",
            &ChiakiPySession::releaseCross, "Release the cross button.")
        .def("press_circle",
            &ChiakiPySession::pressCircle, "Press the circle button.")
        .def("release_circle",
            &ChiakiPySession::releaseCircle, "Release the circle button.")
        .def("press_square",
            &ChiakiPySession::pressSquare, "Press the square button.")
        .def("release_square",
            &ChiakiPySession::releaseSquare, "Release the square button.")
        .def("press_triangle",
            &ChiakiPySession::pressTriangle, "Press the triangle button.")
        .def("release_triangle",
            &ChiakiPySession::releaseTriangle, "Release the triangle button.")
        .def("press_left",
            &ChiakiPySession::pressLeft, "Press the left button.")
        .def("release_left",
            &ChiakiPySession::releaseLeft, "Release the left button.")
        .def("press_right",
            &ChiakiPySession::pressRight, "Press the right button.")
        .def("release_right",
            &ChiakiPySession::releaseRight, "Release the right button.")
        .def("press_up",
            &ChiakiPySession::pressUp, "Press the up button.")
        .def("release_up",
            &ChiakiPySession::releaseUp, "Release the up button.")
        .def("press_down",
            &ChiakiPySession::pressDown, "Press the down button.")
        .def("release_down",
            &ChiakiPySession::releaseDown, "Release the down button.")
        .def("press_l1",
            &ChiakiPySession::pressL1, "Press the L1 button.")
        .def("release_l1",
            &ChiakiPySession::releaseL1, "Release the L1 button.")
        .def("press_r1",
            &ChiakiPySession::pressR1, "Press the R1 button.")
        .def("release_r1",
            &ChiakiPySession::releaseR1, "Release the R1 button.")
        .def("press_l3",
            &ChiakiPySession::pressL3, "Press the L3 button.")
        .def("release_l3",
            &ChiakiPySession::releaseL3, "Release the L3 button.")
        .def("press_r3",
            &ChiakiPySession::pressR3, "Press the R3 button.")
        .def("release_r3",
            &ChiakiPySession::releaseR3, "Release the R3 button.")
        .def("press_options",
            &ChiakiPySession::pressOptions, "Press the options button.")
        .def("release_options",
            &ChiakiPySession::releaseOptions, "Release the options button.")
        .def("press_create",
            &ChiakiPySession::pressCreate, "Press the create button.")
        .def("release_create",
            &ChiakiPySession::releaseCreate, "Release the create button.")
        .def("press_touchpad",
            &ChiakiPySession::pressTouchpad, "Press the touchpad button.")
        .def("release_touchpad",
            &ChiakiPySession::releaseTouchpad, "Release the touchpad button.")
        .def("press_ps",
            &ChiakiPySession::pressPS, "Press the PS button.")
        .def("release_ps",
            &ChiakiPySession::releasePS, "Release the PS button.")
        .def("set_l2",
            &ChiakiPySession::setL2,
            py::arg("state"),
            "Set the L2 trigger state [0, 255].")
        .def("set_r2",
            &ChiakiPySession::setR2,
            py::arg("state"),
            "Set the R2 trigger state [0, 255].")
        .def("set_left_x",
            &ChiakiPySession::setLeftX,
            py::arg("x"),
            "Set the left stick's x value [-32768, 32767], 0 is centered.")
        .def("set_left_y",
            &ChiakiPySession::setLeftY,
            py::arg("y"),
            "Set the left stick's y value [-32768, 32767], 0 is centered.")
        .def("set_left",
            &ChiakiPySession::setLeft,
            py::arg("x"), py::arg("y"),
            "Set the left stick's x and y values [-32768, 32767], 0 is centered.")
        .def("set_right_x",
            &ChiakiPySession::setRightX,
            py::arg("x"),
            "Set the right stick's x value [-32768, 32767], 0 is centered.")
        .def("set_right_y",
            &ChiakiPySession::setRightY,
            py::arg("y"),
            "Set the right stick's y value [-32768, 32767], 0 is centered.")
        .def("set_right",
            &ChiakiPySession::setRight,
            py::arg("x"), py::arg("y"),
            "Set the right stick's x and y values [-32768, 32767], 0 is centered.")
        .def("set_accelerometer_x",
            &ChiakiPySession::setAccelerometerX,
            py::arg("x"),
            "Set the accelerometer x value in g [-5, 5] (at rest: x=0, y=1, z=0).")
        .def("set_accelerometer_y",
            &ChiakiPySession::setAccelerometerY,
            py::arg("y"),
            "Set the accelerometer y value in g [-5, 5] (at rest: x=0, y=1, z=0).")
        .def("set_accelerometer_z",
            &ChiakiPySession::setAccelerometerZ,
            py::arg("z"),
            "Set the accelerometer z value in g [-5, 5] (at rest: x=0, y=1, z=0).")
        .def("set_accelerometer",
            &ChiakiPySession::setAccelerometer,
            py::arg("x"), py::arg("y"), py::arg("z"),
            "Set the accelerometer x, y and z values in g [-5, 5] (at rest: 0, 1, 0).")
        .def("set_gyroscope_x",
            &ChiakiPySession::setGyroscopeX,
            py::arg("x"),
            "Set the gyroscope x value in rad/s [-30, 30] (at rest: 0).")
        .def("set_gyroscope_y",
            &ChiakiPySession::setGyroscopeY,
            py::arg("y"),
            "Set the gyroscope y value in rad/s [-30, 30] (at rest: 0).")
        .def("set_gyroscope_z",
            &ChiakiPySession::setGyroscopeZ,
            py::arg("z"),
            "Set the gyroscope z value in rad/s [-30, 30] (at rest: 0).")
        .def("set_gyroscope",
            &ChiakiPySession::setGyroscope,
            py::arg("x"), py::arg("y"), py::arg("z"),
            "Set the gyroscope x, y and z values in rad/s [-30, 30] (at rest: 0).")
        .def("set_orientation_x",
            &ChiakiPySession::setOrientationX,
            py::arg("x"),
            "Set the orientation quaternion's x component [-1, 1] (at rest: x=y=z=0, w=1).")
        .def("set_orientation_y",
            &ChiakiPySession::setOrientationY,
            py::arg("y"),
            "Set the orientation quaternion's y component [-1, 1] (at rest: x=y=z=0, w=1).")
        .def("set_orientation_z",
            &ChiakiPySession::setOrientationZ,
            py::arg("z"),
            "Set the orientation quaternion's z component [-1, 1] (at rest: x=y=z=0, w=1).")
        .def("set_orientation_w",
            &ChiakiPySession::setOrientationW,
            py::arg("w"),
            "Set the orientation quaternion's w component [-1, 1] (at rest: x=y=z=0, w=1).")
        .def("set_orientation",
            &ChiakiPySession::setOrientation,
            py::arg("x"), py::arg("y"), py::arg("z"), py::arg("w"),
            "Set the orientation as a unit quaternion (x, y, z, w) (at rest: 0, 0, 0, 1).")
        .def("send_feedback_state",
            &ChiakiPySession::SendFeedbackState, "Send the current controller state to the console. The press_*/release_*/set_* methods do this themselves.")
        ;
    // #endif
    ////////////////////    </generated_from:chiakipysession.h>    ////////////////////

    // </litgen_pydef> // Autogenerated code end
}
