// Bindings generated by generate_bindings.py: edit the headers or the generator, not the code between the markers.

#include "pydef.h"

#include "host.h"
#include "discovery_manager.h"

void py_init_discovery(py::module_ &m)
{
    // <litgen_pydef> // Autogenerated code below! Do not edit!
    ////////////////////    <generated_from:host.h>    ////////////////////
    // #ifndef CHIAKI_PY_HOST_H
    //


    auto pyClassHostMAC =
        py::class_<HostMAC>
            (m, "HostMAC", "A console's 6-byte Ethernet MAC address, as used to identify a registered/discovered host.")
        .def("get_mac",
            &HostMAC::GetMAC, py::return_value_policy::reference)
        .def("to_string",
            &HostMAC::ToString)
        .def("get_value",
            &HostMAC::GetValue)
        ;

    pyClassHostMAC.def("__str__", &HostMAC::ToString);


    // #endif
    ////////////////////    </generated_from:host.h>    ////////////////////


    ////////////////////    <generated_from:discovery_manager.h>    ////////////////////
    // #ifndef CHIAKI_PY_DISCOVERYMANAGER_H
    //


    auto pyClassDiscoveryHost =
        py::class_<DiscoveryHost>
            (m, "DiscoveryHost", " One console found by DiscoveryManager's broadcast discovery, or filled in by hand to\n register a manual one. `ps5`, `host_addr` and `state` (whether it's awake or in standby)\n are the fields most callers need; the rest mirrors what the console's discovery reply reports.")
        .def(py::init<>()) // implicit default constructor
        .def_readwrite("ps5", &DiscoveryHost::ps5, "")
        .def_readwrite("state", &DiscoveryHost::state, "")
        .def_readwrite("target", &DiscoveryHost::target, "")
        .def_readwrite("host_request_port", &DiscoveryHost::host_request_port, "")
        .def_readwrite("host_addr", &DiscoveryHost::host_addr, "")
        .def_readwrite("system_version", &DiscoveryHost::system_version, "")
        .def_readwrite("device_discovery_protocol_version", &DiscoveryHost::device_discovery_protocol_version, "")
        .def_readwrite("host_name", &DiscoveryHost::host_name, "")
        .def_readwrite("host_type", &DiscoveryHost::host_type, "")
        .def_readwrite("host_id", &DiscoveryHost::host_id, "")
        .def_readwrite("running_app_titleid", &DiscoveryHost::running_app_titleid, "")
        .def_readwrite("running_app_name", &DiscoveryHost::running_app_name, "")
        .def("get_host_mac",
            &DiscoveryHost::GetHostMAC, "The host's MAC address, parsed from host_id.")
        ;


    auto pyClassDiscoveryManager =
        py::class_<DiscoveryManager>
            (m, "DiscoveryManager", " Broadcasts for PS4/PS5 hosts on the local network (IPv4 and IPv6) in the background and keeps\n track of what answered. `chiaki_py.discover_hosts()` wraps the start/wait/collect/stop sequence\n this class otherwise requires driving by hand.")
        .def(py::init<>())
        .def("set_active",
            &DiscoveryManager::SetActive,
            py::arg("active"),
            " Start or stop broadcasting. Starting re-inits the discovery sockets if they were not\n already active; stopping tears them down and clears the discovered host list.")
        .def("send_wakeup",
            &DiscoveryManager::SendWakeup,
            py::arg("host"), py::arg("regist_key"), py::arg("ps5"),
            " Send a wakeup packet to `host` (a registration's `regist_key`, hex-encoded) so a console\n in standby powers on. Raises ValueError if `regist_key` isn't hex, and RuntimeError if it is\n too long or sending fails.")
        .def("get_active",
            &DiscoveryManager::GetActive, "Whether broadcast discovery is currently running.")
        .def("get_hosts",
            &DiscoveryManager::GetHosts, "The hosts the last broadcast round found. Empty until set_active(True) has had time to hear back.")
        .def("discovery_service_hosts",
            &DiscoveryManager::DiscoveryServiceHosts,
            py::arg("hosts"),
            " Replace the broadcast-discovered host list wholesale. Called internally as broadcast replies\n come in; not normally needed from Python.")
        .def("hosts_updated",
            &DiscoveryManager::HostsUpdated)
        ;
    // #endif
    ////////////////////    </generated_from:discovery_manager.h>    ////////////////////

    // </litgen_pydef> // Autogenerated code end
}
