// Bindings generated by generate_bindings.py: edit the headers or the generator, not the code between the markers.

#include "pydef.h"

#include "settings.h"

#include <sstream>

void py_init_settings(py::module_ &m)
{
    // <litgen_pydef> // Autogenerated code below! Do not edit!
    ////////////////////    <generated_from:settings.h>    ////////////////////
    // #ifndef CHIAKI_PY_SETTINGS_H
    //


    auto pyEnumRumbleHapticsIntensity =
        py::enum_<RumbleHapticsIntensity>(m, "RumbleHapticsIntensity", py::arithmetic(), "How strongly the controller rumbles for haptic feedback, from Settings.get/set_rumble_haptics_intensity().")
            .value("Off", RumbleHapticsIntensity::Off, "")
            .value("VeryWeak", RumbleHapticsIntensity::VeryWeak, "")
            .value("Weak", RumbleHapticsIntensity::Weak, "")
            .value("Normal", RumbleHapticsIntensity::Normal, "")
            .value("Strong", RumbleHapticsIntensity::Strong, "")
            .value("VeryStrong", RumbleHapticsIntensity::VeryStrong, "")
        .export_values();


    auto pyEnumDecoder =
        py::enum_<Decoder>(m, "Decoder", py::arithmetic(), " The decoder implementation stored by Settings.get/set_decoder(). Only Ffmpeg is implemented and\n it is always used, whatever is set; Pi (chiaki-ng's Raspberry Pi decoder) is accepted but ignored.")
            .value("Ffmpeg", Decoder::Ffmpeg, "")
            .value("Pi", Decoder::Pi, "")
        .export_values();


    auto pyClassSettings =
        py::class_<Settings>
            (m, "Settings", " In-memory connection/decoding/UI settings, passed to ChiakiPySessionConnectInfo.\n A fresh instance starts at chiaki-ng's defaults; nothing is persisted. Most get_/set_ pairs\n are self-explanatory config knobs; set_log_level()/set_log_verbose() are the ones most callers\n need to touch directly (chiaki_py.Session sets the hardware decoder from its frame_handler_cls).")
        .def(py::init<>())
        .def("get_audio_video_disabled",
            &Settings::GetAudioVideoDisabled)
        .def("get_log_verbose",
            &Settings::GetLogVerbose)
        .def("set_log_verbose",
            &Settings::SetLogVerbose, py::arg("log_verbose"))
        .def("get_log_level",
            &Settings::GetLogLevel, " The least severe log level that is still logged; the levels are single bits ordered\n ERROR < WARNING < INFO < VERBOSE < DEBUG.")
        .def("set_log_level",
            &Settings::SetLogLevel,
            py::arg("log_level"),
            " Set the least severe log level that is still logged, e.g. LogLevel.DEBUG to see\n everything. Defaults to LogLevel.WARNING (LogLevel.DEBUG in a debug build of the module).\n VERBOSE is additionally controlled by set_log_verbose.")
        .def("get_log_level_mask",
            &Settings::GetLogLevelMask)
        .def("get_rumble_haptics_intensity",
            &Settings::GetRumbleHapticsIntensity)
        .def("set_rumble_haptics_intensity",
            &Settings::SetRumbleHapticsIntensity, py::arg("rumble_haptics_intensity"))
        .def("get_buttons_by_position",
            &Settings::GetButtonsByPosition)
        .def("set_buttons_by_position",
            &Settings::SetButtonsByPosition, py::arg("buttons_by_position"))
        .def("get_start_mic_unmuted",
            &Settings::GetStartMicUnmuted)
        .def("set_start_mic_unmuted",
            &Settings::SetStartMicUnmuted, py::arg("start_mic_unmuted"))
        .def("get_haptic_override",
            &Settings::GetHapticOverride)
        .def("set_haptic_override",
            &Settings::SetHapticOverride, py::arg("haptic_override"))
        .def("get_resolution_local_ps4",
            &Settings::GetResolutionLocalPS4)
        .def("get_resolution_remote_ps4",
            &Settings::GetResolutionRemotePS4)
        .def("get_resolution_local_ps5",
            &Settings::GetResolutionLocalPS5)
        .def("get_resolution_remote_ps5",
            &Settings::GetResolutionRemotePS5)
        .def("set_resolution_local_ps4",
            &Settings::SetResolutionLocalPS4, py::arg("resolution_local_ps4"))
        .def("set_resolution_remote_ps4",
            &Settings::SetResolutionRemotePS4, py::arg("resolution_remote_ps4"))
        .def("set_resolution_local_ps5",
            &Settings::SetResolutionLocalPS5, py::arg("resolution_local_ps5"))
        .def("set_resolution_remote_ps5",
            &Settings::SetResolutionRemotePS5, py::arg("resolution_remote_ps5"))
        .def("get_fpslocal_ps4",
            &Settings::GetFPSLocalPS4)
        .def("get_fpsremote_ps4",
            &Settings::GetFPSRemotePS4)
        .def("get_fpslocal_ps5",
            &Settings::GetFPSLocalPS5)
        .def("get_fpsremote_ps5",
            &Settings::GetFPSRemotePS5)
        .def("set_fpslocal_ps4",
            &Settings::SetFPSLocalPS4, py::arg("fps_local_ps4"))
        .def("set_fpsremote_ps4",
            &Settings::SetFPSRemotePS4, py::arg("fps_remote_ps4"))
        .def("set_fpslocal_ps5",
            &Settings::SetFPSLocalPS5, py::arg("fps_local_ps5"))
        .def("set_fpsremote_ps5",
            &Settings::SetFPSRemotePS5, py::arg("fps_remote_ps5"))
        .def("get_bitrate_local_ps4",
            &Settings::GetBitrateLocalPS4)
        .def("get_bitrate_remote_ps4",
            &Settings::GetBitrateRemotePS4)
        .def("get_bitrate_local_ps5",
            &Settings::GetBitrateLocalPS5)
        .def("get_bitrate_remote_ps5",
            &Settings::GetBitrateRemotePS5)
        .def("set_bitrate_local_ps4",
            &Settings::SetBitrateLocalPS4, py::arg("bitrate_local_ps4"))
        .def("set_bitrate_remote_ps4",
            &Settings::SetBitrateRemotePS4, py::arg("bitrate_remote_ps4"))
        .def("set_bitrate_local_ps5",
            &Settings::SetBitrateLocalPS5, py::arg("bitrate_local_ps5"))
        .def("set_bitrate_remote_ps5",
            &Settings::SetBitrateRemotePS5, py::arg("bitrate_remote_ps5"))
        .def("get_codec_ps4",
            &Settings::GetCodecPS4)
        .def("get_codec_local_ps5",
            &Settings::GetCodecLocalPS5)
        .def("get_codec_remote_ps5",
            &Settings::GetCodecRemotePS5)
        .def("set_codec_ps4",
            &Settings::SetCodecPS4, py::arg("codec_ps4"))
        .def("set_codec_local_ps5",
            &Settings::SetCodecLocalPS5, py::arg("codec_local_ps5"))
        .def("set_codec_remote_ps5",
            &Settings::SetCodecRemotePS5, py::arg("codec_remote_ps5"))
        .def("get_display_target_contrast",
            &Settings::GetDisplayTargetContrast)
        .def("set_display_target_contrast",
            &Settings::SetDisplayTargetContrast, py::arg("display_target_contrast"))
        .def("get_display_target_peak",
            &Settings::GetDisplayTargetPeak)
        .def("set_display_target_peak",
            &Settings::SetDisplayTargetPeak, py::arg("display_target_peak"))
        .def("get_display_target_trc",
            &Settings::GetDisplayTargetTrc)
        .def("set_display_target_trc",
            &Settings::SetDisplayTargetTrc, py::arg("display_target_trc"))
        .def("get_display_target_prim",
            &Settings::GetDisplayTargetPrim)
        .def("set_display_target_prim",
            &Settings::SetDisplayTargetPrim, py::arg("display_target_prim"))
        .def("get_decoder",
            &Settings::GetDecoder)
        .def("set_decoder",
            &Settings::SetDecoder,
            py::arg("decoder"),
            "Currently ignored, see Decoder.")
        .def("get_hardware_decoder",
            &Settings::GetHardwareDecoder)
        .def("set_hardware_decoder",
            &Settings::SetHardwareDecoder, py::arg("hardware_decoder"))
        .def("get_packet_loss_max",
            &Settings::GetPacketLossMax)
        .def("set_packet_loss_max",
            &Settings::SetPacketLossMax, py::arg("packet_loss_max"))
        .def("get_audio_volume",
            &Settings::GetAudioVolume)
        .def("set_audio_volume",
            &Settings::SetAudioVolume,
            py::arg("audio_volume"),
            "Stored only: playback does not apply it yet.")
        .def("get_audio_buffer_size_default",
            &Settings::GetAudioBufferSizeDefault)
        .def("get_audio_buffer_size_raw",
            &Settings::GetAudioBufferSizeRaw, "The audio buffer size as set, 0 if set to \"automatic\".")
        .def("get_audio_buffer_size",
            &Settings::GetAudioBufferSize, "The audio buffer size to use: the default one if get_audio_buffer_size_raw() is 0.")
        .def("set_audio_buffer_size",
            &Settings::SetAudioBufferSize, py::arg("audio_buffer_size"))
        .def("get_audio_out_device",
            &Settings::GetAudioOutDevice)
        .def("set_audio_out_device",
            &Settings::SetAudioOutDevice,
            py::arg("audio_out_device"),
            "Stored only: pass the device to chiaki_py.AudioSink or AudioOutput.open() instead.")
        .def("get_audio_in_device",
            &Settings::GetAudioInDevice)
        .def("set_audio_in_device",
            &Settings::SetAudioInDevice,
            py::arg("audio_in_device"),
            "Stored only: there is no microphone input yet.")
        .def("get_psn_auth_token",
            &Settings::GetPsnAuthToken)
        .def("set_psn_auth_token",
            &Settings::SetPsnAuthToken, py::arg("psn_auth_token"))
        .def("get_dpad_touch_enabled",
            &Settings::GetDpadTouchEnabled)
        .def("set_dpad_touch_enabled",
            &Settings::SetDpadTouchEnabled, py::arg("dpad_touch_enabled"))
        .def("get_dpad_touch_increment",
            &Settings::GetDpadTouchIncrement)
        .def("set_dpad_touch_increment",
            &Settings::SetDpadTouchIncrement, py::arg("dpad_touch_increment"))
        .def("get_dpad_touch_shortcut1",
            &Settings::GetDpadTouchShortcut1)
        .def("set_dpad_touch_shortcut1",
            &Settings::SetDpadTouchShortcut1, py::arg("dpad_touch_shortcut1"))
        .def("get_dpad_touch_shortcut2",
            &Settings::GetDpadTouchShortcut2)
        .def("set_dpad_touch_shortcut2",
            &Settings::SetDpadTouchShortcut2, py::arg("dpad_touch_shortcut2"))
        .def("get_dpad_touch_shortcut3",
            &Settings::GetDpadTouchShortcut3)
        .def("set_dpad_touch_shortcut3",
            &Settings::SetDpadTouchShortcut3, py::arg("dpad_touch_shortcut3"))
        .def("get_dpad_touch_shortcut4",
            &Settings::GetDpadTouchShortcut4)
        .def("set_dpad_touch_shortcut4",
            &Settings::SetDpadTouchShortcut4, py::arg("dpad_touch_shortcut4"))
        .def("get_psn_account_id",
            &Settings::GetPsnAccountId)
        .def("set_psn_account_id",
            &Settings::SetPsnAccountId, py::arg("psn_account_id"))
        .def("get_video_profile_local_ps4",
            &Settings::GetVideoProfileLocalPS4)
        .def("get_video_profile_remote_ps4",
            &Settings::GetVideoProfileRemotePS4)
        .def("get_video_profile_local_ps5",
            &Settings::GetVideoProfileLocalPS5)
        .def("get_video_profile_remote_ps5",
            &Settings::GetVideoProfileRemotePS5)
        .def_static("get_chiaki_controller_button_name",
            &Settings::GetChiakiControllerButtonName, py::arg("chiaki_button"))
        .def("set_controller_button_mapping",
            &Settings::SetControllerButtonMapping, py::arg("chiaki_button"), py::arg("key"))
        .def("get_controller_mapping",
            &Settings::GetControllerMapping)
        .def("get_controller_mapping_for_decoding",
            &Settings::GetControllerMappingForDecoding)
        .def("get_registered_host_registered",
            &Settings::GetRegisteredHostRegistered, py::arg("mac"))
        .def("get_manual_hosts",
            &Settings::GetManualHosts)
        ;

    pyClassSettings.def("__repr__", [](const Settings &s)
    {
        std::ostringstream repr;
        repr << "<Settings("
             << "logVerbose=" << (s.GetLogVerbose() ? "True" : "False") << ", "
             << "logLevelMask=" << s.GetLogLevelMask() << ", "
             << "rumbleHapticsIntensity=" << static_cast<int>(s.GetRumbleHapticsIntensity()) << ", "
             << "buttonsByPosition=" << (s.GetButtonsByPosition() ? "True" : "False") << ", "
             << "startMicUnmuted=" << (s.GetStartMicUnmuted() ? "True" : "False") << ", "
             << "hapticOverride=" << s.GetHapticOverride() << ", "
             << "resolutionLocalPS4=" << static_cast<int>(s.GetResolutionLocalPS4()) << ", "
             << "resolutionRemotePS4=" << static_cast<int>(s.GetResolutionRemotePS4()) << ", "
             << "fpsLocalPS4=" << static_cast<int>(s.GetFPSLocalPS4()) << ", "
             << "fpsRemotePS4=" << static_cast<int>(s.GetFPSRemotePS4()) << ", "
             << "bitrateLocalPS4=" << s.GetBitrateLocalPS4() << ", "
             << "bitrateRemotePS4=" << s.GetBitrateRemotePS4() << ", "
             << "codecPS4=" << static_cast<int>(s.GetCodecPS4()) << ", "
             << "decoder=" << static_cast<int>(s.GetDecoder()) << ", "
             << "hardwareDecoder='" << s.GetHardwareDecoder() << "', "
             << "packetLossMax=" << s.GetPacketLossMax() << ", "
             << "audioVolume=" << s.GetAudioVolume() << ", "
             << "audioBufferSize=" << s.GetAudioBufferSize() << ", "
             << "audioOutDevice='" << s.GetAudioOutDevice() << "', "
             << "audioInDevice='" << s.GetAudioInDevice() << "', "
             << "psnAccountId='" << s.GetPsnAccountId() << "'"
             << ")>";
        return repr.str();
    });


    // #endif
    ////////////////////    </generated_from:settings.h>    ////////////////////

    // </litgen_pydef> // Autogenerated code end
}
