// Bindings generated by generate_bindings.py: edit the headers or the generator, not the code between the markers.

#include "pydef.h"

#include "audio_handler.h"
#include "audio_output.h"
#include "chiakipysession.h"

void py_init_audio(py::module_ &m)
{
    // <litgen_pydef> // Autogenerated code below! Do not edit!
    ////////////////////    <generated_from:audio_handler.h>    ////////////////////
    // #ifndef CHIAKI_PY_AUDIO_HANDLER_H
    //


    auto pyClassAudioHandler =
        py::class_<AudioHandler>
            (m, "AudioHandler", " The queue of a ChiakiPySession's decoded audio (interleaved int16 PCM), as returned by\n ChiakiPySession.get_audio_handler(). Every read removes the frames it returns, so use one\n consumer only: get_frame(), an AudioOutput or chiaki_py.AudioSink.")
        .def("queue_frame",
            &AudioHandler::QueueFrame, py::arg("buf"), py::arg("samples_count"))
        .def("get_frame",
            &AudioHandler::GetFrame,
            py::arg("max_frames") = 0,
            " Remove and return up to max_frames queued audio frames (0 = all) as an int16 array of shape\n (frames, channels), or of shape (0, 0) if none are queued.")
        .def("read_frames",
            &AudioHandler::ReadFrames, py::arg("out"), py::arg("max_frames"))
        .def("get_audio_queued_frames",
            &AudioHandler::GetAudioQueuedFrames, "The number of audio frames waiting in the queue.")
        .def("clear_audio_queue",
            &AudioHandler::ClearAudioQueue, "Drop every queued audio frame.")
        .def("get_audio_queue_max_frames",
            &AudioHandler::GetAudioQueueMaxFrames, "The queue capacity in frames; the oldest frames are dropped beyond it.")
        .def("set_audio_queue_max_frames",
            &AudioHandler::SetAudioQueueMaxFrames,
            py::arg("max_frames"),
            "Set the queue capacity in frames (0 = 3x the audio buffer size from Settings).")
        .def("get_audio_channels",
            &AudioHandler::GetAudioChannels, "The number of audio channels; 0 until the first audio frame arrived.")
        .def("get_audio_rate",
            &AudioHandler::GetAudioRate, "The audio sample rate in Hz; 0 until the first audio frame arrived.")
        ;
    // #endif
    ////////////////////    </generated_from:audio_handler.h>    ////////////////////


    ////////////////////    <generated_from:audio_output.h>    ////////////////////
    // #ifndef CHIAKI_PY_AUDIO_OUTPUT_H
    //


    auto pyClassAudioOutput =
        py::class_<AudioOutput>
            (m, "AudioOutput", " Plays a session's audio on an SDL output device. SDL's audio thread takes the frames straight\n off the session's AudioHandler queue, without the GIL, so don't read that queue anywhere else\n while it is open. chiaki_py.AudioSink wraps it.\n\n SDL calls back into C++ for exactly as many frames as the device needs, so playback never waits\n for the GIL. SDL loads the platform's audio backend (WASAPI, CoreAudio, PulseAudio/PipeWire,\n ALSA) at runtime, so nothing beyond the SDL library bundled with the module is needed.")
        .def("open",
            &AudioOutput::Open,
            py::arg("device_name") = "",
            " Open the output device (a name from get_devices(), '' = the system default) at the session's audio\n rate and channel count and start playing. Raises RuntimeError before the first audio frame arrived,\n or if the device can't be opened.",
            py::call_guard<py::gil_scoped_release>())
        .def("close",
            &AudioOutput::Close,
            "Stop playing and close the device. Does nothing if it isn't open.",
            py::call_guard<py::gil_scoped_release>())
        .def("is_open",
            &AudioOutput::IsOpen, "Whether the device is open.")
        .def_static("get_devices",
            &AudioOutput::GetDevices, "Names of the available audio output devices.")
        ;

    pyClassAudioOutput.def(py::init([](ChiakiPySession &session) { return new AudioOutput(session.GetAudioHandler()); }),
                 py::arg("session"), py::keep_alive<1, 2>());


    // #endif
    ////////////////////    </generated_from:audio_output.h>    ////////////////////

    // </litgen_pydef> // Autogenerated code end
}
